/*
 Copyright (C) 2016 Alexander Borisov

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

 Author: lex.borisov@gmail.com (Alexander Borisov)
*/

#ifndef MyHTML_MyCSS_PROPERTY_RESOURCES_H
#define MyHTML_MyCSS_PROPERTY_RESOURCES_H
#pragma once

#define MyCSS_PROPERTY_STATIC_INDEX_FOR_SEARCH_SIZE 263
#define MyCSS_PROPERTY_VALUE_STATIC_INDEX_FOR_SEARCH_SIZE 227

static const mycss_property_index_static_entry_t mycss_property_index_static_for_search[] = 
{
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"flex-basis", 10, MyCSS_PROPERTY_TYPE_FLEX_BASIS, mycss_property_parser_flex_basis, 264, 3},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"font-stretch", 12, MyCSS_PROPERTY_TYPE_FONT_STRETCH, mycss_property_parser_font_stretch, 267, 5},
	{"animation-play-state", 20, MyCSS_PROPERTY_TYPE_ANIMATION_PLAY_STATE, mycss_property_parser_animation_play_state, 0, 6},
	{"columns", 7, MyCSS_PROPERTY_TYPE_COLUMNS, mycss_property_parser_columns, 268, 7},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-width", 12, MyCSS_PROPERTY_TYPE_BORDER_WIDTH, mycss_property_parser_border_width, 0, 10},
	{"caret-color", 11, MyCSS_PROPERTY_TYPE_CARET_COLOR, mycss_property_parser_caret_color, 269, 11},
	{"padding", 7, MyCSS_PROPERTY_TYPE_PADDING, mycss_property_parser_padding, 0, 12},
	{"border-top-width", 16, MyCSS_PROPERTY_TYPE_BORDER_TOP_WIDTH, mycss_property_parser_border_top_width, 0, 13},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"display", 7, MyCSS_PROPERTY_TYPE_DISPLAY, mycss_property_parser_display, 270, 15},
	{"cue", 3, MyCSS_PROPERTY_TYPE_CUE, mycss_property_parser_cue, 271, 16},
	{"nav-down", 8, MyCSS_PROPERTY_TYPE_NAV_DOWN, mycss_property_parser_nav_down, 272, 17},
	{"nav-up", 6, MyCSS_PROPERTY_TYPE_NAV_UP, mycss_property_parser_nav_up, 273, 18},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-radius", 13, MyCSS_PROPERTY_TYPE_BORDER_RADIUS, mycss_property_parser_border_radius, 0, 20},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"word-wrap", 9, MyCSS_PROPERTY_TYPE_WORD_WRAP, mycss_property_parser_word_wrap, 0, 25},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"voice-balance", 13, MyCSS_PROPERTY_TYPE_VOICE_BALANCE, mycss_property_parser_voice_balance, 275, 28},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"rest", 4, MyCSS_PROPERTY_TYPE_REST, mycss_property_parser_rest, 276, 34},
	{"list-style-type", 15, MyCSS_PROPERTY_TYPE_LIST_STYLE_TYPE, mycss_property_parser_list_style_type, 0, 35},
	{"animation", 9, MyCSS_PROPERTY_TYPE_ANIMATION, mycss_property_parser_animation, 278, 36},
	{"nav-left", 8, MyCSS_PROPERTY_TYPE_NAV_LEFT, mycss_property_parser_nav_left, 279, 37},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"word-break", 10, MyCSS_PROPERTY_TYPE_WORD_BREAK, mycss_property_parser_word_break, 280, 39},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"continue", 8, MyCSS_PROPERTY_TYPE_CONTINUE, mycss_property_parser_continue, 283, 41},
	{"voice-rate", 10, MyCSS_PROPERTY_TYPE_VOICE_RATE, mycss_property_parser_voice_rate, 284, 42},
	{"flex", 4, MyCSS_PROPERTY_TYPE_FLEX, mycss_property_parser_flex, 286, 43},
	{"voice-stress", 12, MyCSS_PROPERTY_TYPE_VOICE_STRESS, mycss_property_parser_voice_stress, 0, 44},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"transition", 10, MyCSS_PROPERTY_TYPE_TRANSITION, mycss_property_parser_transition, 288, 46},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"margin-top", 10, MyCSS_PROPERTY_TYPE_MARGIN_TOP, mycss_property_parser_margin_top, 289, 49},
	{"shape-margin", 12, MyCSS_PROPERTY_TYPE_SHAPE_MARGIN, mycss_property_parser_shape_margin, 0, 50},
	{"cue-before", 10, MyCSS_PROPERTY_TYPE_CUE_BEFORE, mycss_property_parser_cue_before, 290, 51},
	{"column-fill", 11, MyCSS_PROPERTY_TYPE_COLUMN_FILL, mycss_property_parser_column_fill, 291, 52},
	{"top", 3, MyCSS_PROPERTY_TYPE_TOP, mycss_property_parser_top, 292, 53},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"widows", 6, MyCSS_PROPERTY_TYPE_WIDOWS, mycss_property_parser_widows, 293, 55},
	{"caret-shape", 11, MyCSS_PROPERTY_TYPE_CARET_SHAPE, mycss_property_parser_caret_shape, 295, 56},
	{"cue-after", 9, MyCSS_PROPERTY_TYPE_CUE_AFTER, mycss_property_parser_cue_after, 296, 57},
	{"font-variant-ligatures", 22, MyCSS_PROPERTY_TYPE_FONT_VARIANT_LIGATURES, mycss_property_parser_font_variant_ligatures, 298, 58},
	{"box-suppress", 12, MyCSS_PROPERTY_TYPE_BOX_SUPPRESS, mycss_property_parser_box_suppress, 299, 59},
	{"height", 6, MyCSS_PROPERTY_TYPE_HEIGHT, mycss_property_parser_height, 300, 60},
	{"caption-side", 12, MyCSS_PROPERTY_TYPE_CAPTION_SIDE, mycss_property_parser_caption_side, 0, 61},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"list-style-position", 19, MyCSS_PROPERTY_TYPE_LIST_STYLE_POSITION, mycss_property_parser_list_style_position, 301, 67},
	{"word-spacing", 12, MyCSS_PROPERTY_TYPE_WORD_SPACING, mycss_property_parser_word_spacing, 0, 68},
	{"animation-timing-function", 25, MyCSS_PROPERTY_TYPE_ANIMATION_TIMING_FUNCTION, mycss_property_parser_animation_timing_function, 0, 69},
	{"flex-direction", 14, MyCSS_PROPERTY_TYPE_FLEX_DIRECTION, mycss_property_parser_flex_direction, 302, 70},
	{"animation-duration", 18, MyCSS_PROPERTY_TYPE_ANIMATION_DURATION, mycss_property_parser_animation_duration, 0, 71},
	{"break-after", 11, MyCSS_PROPERTY_TYPE_BREAK_AFTER, mycss_property_parser_break_after, 304, 72},
	{"margin-bottom", 13, MyCSS_PROPERTY_TYPE_MARGIN_BOTTOM, mycss_property_parser_margin_bottom, 305, 73},
	{"voice-pitch", 11, MyCSS_PROPERTY_TYPE_VOICE_PITCH, mycss_property_parser_voice_pitch, 0, 74},
	{"speak-as", 8, MyCSS_PROPERTY_TYPE_SPEAK_AS, mycss_property_parser_speak_as, 307, 75},
	{"width", 5, MyCSS_PROPERTY_TYPE_WIDTH, mycss_property_parser_width, 0, 76},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"justify-content", 15, MyCSS_PROPERTY_TYPE_JUSTIFY_CONTENT, mycss_property_parser_justify_content, 309, 78},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"indent-edge-reset", 17, MyCSS_PROPERTY_TYPE_INDENT_EDGE_RESET, mycss_property_parser_indent_edge_reset, 0, 80},
	{"border-bottom-width", 19, MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_WIDTH, mycss_property_parser_border_bottom_width, 0, 81},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"counter-increment", 17, MyCSS_PROPERTY_TYPE_COUNTER_INCREMENT, mycss_property_parser_counter_increment, 0, 83},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-spacing", 14, MyCSS_PROPERTY_TYPE_BORDER_SPACING, mycss_property_parser_border_spacing, 310, 86},
	{"caret", 5, MyCSS_PROPERTY_TYPE_CARET, mycss_property_parser_caret, 311, 87},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-top", 10, MyCSS_PROPERTY_TYPE_BORDER_TOP, mycss_property_parser_border_top, 0, 90},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"text-emphasis-color", 19, MyCSS_PROPERTY_TYPE_TEXT_EMPHASIS_COLOR, mycss_property_parser_text_emphasis_color, 0, 92},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"text-shadow", 11, MyCSS_PROPERTY_TYPE_TEXT_SHADOW, mycss_property_parser_text_shadow, 0, 94},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"font-kerning", 12, MyCSS_PROPERTY_TYPE_FONT_KERNING, mycss_property_parser_font_kerning, 0, 96},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"flex-grow", 9, MyCSS_PROPERTY_TYPE_FLEX_GROW, mycss_property_parser_flex_grow, 313, 98},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"text-emphasis-position", 22, MyCSS_PROPERTY_TYPE_TEXT_EMPHASIS_POSITION, mycss_property_parser_text_emphasis_position, 0, 100},
	{"tab-size", 8, MyCSS_PROPERTY_TYPE_TAB_SIZE, mycss_property_parser_tab_size, 0, 101},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"outline", 7, MyCSS_PROPERTY_TYPE_OUTLINE, mycss_property_parser_outline, 315, 104},
	{"writing-mode", 12, MyCSS_PROPERTY_TYPE_WRITING_MODE, mycss_property_parser_writing_mode, 317, 105},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"text-emphasis-style", 19, MyCSS_PROPERTY_TYPE_TEXT_EMPHASIS_STYLE, mycss_property_parser_text_emphasis_style, 0, 107},
	{"right", 5, MyCSS_PROPERTY_TYPE_RIGHT, mycss_property_parser_right, 318, 108},
	{"font-synthesis", 14, MyCSS_PROPERTY_TYPE_FONT_SYNTHESIS, mycss_property_parser_font_synthesis, 320, 109},
	{"outline-offset", 14, MyCSS_PROPERTY_TYPE_OUTLINE_OFFSET, mycss_property_parser_outline_offset, 321, 110},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"box-shadow", 10, MyCSS_PROPERTY_TYPE_BOX_SHADOW, mycss_property_parser_box_shadow, 0, 112},
	{"direction", 9, MyCSS_PROPERTY_TYPE_DIRECTION, mycss_property_parser_direction, 322, 113},
	{"border-right-style", 18, MyCSS_PROPERTY_TYPE_BORDER_RIGHT_STYLE, mycss_property_parser_border_right_style, 323, 114},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"inline-size-step", 16, MyCSS_PROPERTY_TYPE_INLINE_SIZE_STEP, mycss_property_parser_inline_size_step, 0, 116},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"transition-timing-function", 26, MyCSS_PROPERTY_TYPE_TRANSITION_TIMING_FUNCTION, mycss_property_parser_transition_timing_function, 0, 118},
	{"marker-mid", 10, MyCSS_PROPERTY_TYPE_MARKER_MID, mycss_property_parser_marker_mid, 324, 119},
	{"marker-side", 11, MyCSS_PROPERTY_TYPE_MARKER_SIDE, mycss_property_parser_marker_side, 325, 120},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"quotes", 6, MyCSS_PROPERTY_TYPE_QUOTES, mycss_property_parser_quotes, 326, 123},
	{"border-left", 11, MyCSS_PROPERTY_TYPE_BORDER_LEFT, mycss_property_parser_border_left, 328, 124},
	{"voice-range", 11, MyCSS_PROPERTY_TYPE_VOICE_RANGE, mycss_property_parser_voice_range, 0, 125},
	{"cursor", 6, MyCSS_PROPERTY_TYPE_CURSOR, mycss_property_parser_cursor, 329, 126},
	{"opacity", 7, MyCSS_PROPERTY_TYPE_OPACITY, mycss_property_parser_opacity, 330, 127},
	{"marker", 6, MyCSS_PROPERTY_TYPE_MARKER, mycss_property_parser_marker, 331, 128},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"offset-start", 12, MyCSS_PROPERTY_TYPE_OFFSET_START, mycss_property_parser_offset_start, 0, 132},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"appearance", 10, MyCSS_PROPERTY_TYPE_APPEARANCE, mycss_property_parser_appearance, 333, 135},
	{"animation-name", 14, MyCSS_PROPERTY_TYPE_ANIMATION_NAME, mycss_property_parser_animation_name, 334, 136},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"column-rule-width", 17, MyCSS_PROPERTY_TYPE_COLUMN_RULE_WIDTH, mycss_property_parser_column_rule_width, 0, 138},
	{"border-collapse", 15, MyCSS_PROPERTY_TYPE_BORDER_COLLAPSE, mycss_property_parser_border_collapse, 335, 139},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"unicode-bidi", 12, MyCSS_PROPERTY_TYPE_UNICODE_BIDI, mycss_property_parser_unicode_bidi, 336, 141},
	{"margin", 6, MyCSS_PROPERTY_TYPE_MARGIN, mycss_property_parser_margin, 0, 142},
	{"left", 4, MyCSS_PROPERTY_TYPE_LEFT, mycss_property_parser_left, 337, 143},
	{"fill", 4, MyCSS_PROPERTY_TYPE_FILL, mycss_property_parser_fill, 0, 144},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-right-width", 18, MyCSS_PROPERTY_TYPE_BORDER_RIGHT_WIDTH, mycss_property_parser_border_right_width, 340, 146},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"align-items", 11, MyCSS_PROPERTY_TYPE_ALIGN_ITEMS, mycss_property_parser_align_items, 0, 148},
	{"color", 5, MyCSS_PROPERTY_TYPE_COLOR, mycss_property_parser_color, 341, 149},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"order", 5, MyCSS_PROPERTY_TYPE_ORDER, mycss_property_parser_order, 342, 151},
	{"rest-before", 11, MyCSS_PROPERTY_TYPE_REST_BEFORE, mycss_property_parser_rest_before, 343, 152},
	{"color-rendering", 15, MyCSS_PROPERTY_TYPE_COLOR_RENDERING, mycss_property_parser_color_rendering, 0, 153},
	{"animation-iteration-count", 25, MyCSS_PROPERTY_TYPE_ANIMATION_ITERATION_COUNT, mycss_property_parser_animation_iteration_count, 0, 154},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-top-right-radius", 23, MyCSS_PROPERTY_TYPE_BORDER_TOP_RIGHT_RADIUS, mycss_property_parser_border_top_right_radius, 0, 156},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"wrap-flow", 9, MyCSS_PROPERTY_TYPE_WRAP_FLOW, mycss_property_parser_wrap_flow, 344, 158},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"list-style-image", 16, MyCSS_PROPERTY_TYPE_LIST_STYLE_IMAGE, mycss_property_parser_list_style_image, 0, 160},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"outline-width", 13, MyCSS_PROPERTY_TYPE_OUTLINE_WIDTH, mycss_property_parser_outline_width, 345, 163},
	{"break-before", 12, MyCSS_PROPERTY_TYPE_BREAK_BEFORE, mycss_property_parser_break_before, 348, 164},
	{"background", 10, MyCSS_PROPERTY_TYPE_BACKGROUND, mycss_property_parser_background, 351, 165},
	{"stroke-linecap", 14, MyCSS_PROPERTY_TYPE_STROKE_LINECAP, mycss_property_parser_stroke_linecap, 0, 166},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"user-select", 11, MyCSS_PROPERTY_TYPE_USER_SELECT, mycss_property_parser_user_select, 0, 172},
	{"nav-right", 9, MyCSS_PROPERTY_TYPE_NAV_RIGHT, mycss_property_parser_nav_right, 352, 173},
	{"z-index", 7, MyCSS_PROPERTY_TYPE_Z_INDEX, mycss_property_parser_z_index, 353, 174},
	{"backface-visibility", 19, MyCSS_PROPERTY_TYPE_BACKFACE_VISIBILITY, mycss_property_parser_backface_visibility, 0, 175},
	{"background-color", 16, MyCSS_PROPERTY_TYPE_BACKGROUND_COLOR, mycss_property_parser_background_color, 354, 176},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"resize", 6, MyCSS_PROPERTY_TYPE_RESIZE, mycss_property_parser_resize, 0, 179},
	{"scroll-snap-align", 17, MyCSS_PROPERTY_TYPE_SCROLL_SNAP_ALIGN, mycss_property_parser_scroll_snap_align, 0, 180},
	{"transform", 9, MyCSS_PROPERTY_TYPE_TRANSFORM, mycss_property_parser_transform, 355, 181},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-right", 12, MyCSS_PROPERTY_TYPE_BORDER_RIGHT, mycss_property_parser_border_right, 0, 183},
	{"bottom", 6, MyCSS_PROPERTY_TYPE_BOTTOM, mycss_property_parser_bottom, 357, 184},
	{"text-decoration-styl", 20, MyCSS_PROPERTY_TYPE_TEXT_DECORATION_STYL, mycss_property_parser_text_decoration_styl, 0, 185},
	{"stroke-width", 12, MyCSS_PROPERTY_TYPE_STROKE_WIDTH, mycss_property_parser_stroke_width, 0, 186},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"font-style", 10, MyCSS_PROPERTY_TYPE_FONT_STYLE, mycss_property_parser_font_style, 359, 188},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"stroke-opacity", 14, MyCSS_PROPERTY_TYPE_STROKE_OPACITY, mycss_property_parser_stroke_opacity, 0, 191},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"color-interpolation", 19, MyCSS_PROPERTY_TYPE_COLOR_INTERPOLATION, mycss_property_parser_color_interpolation, 0, 193},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-top-left-radius", 22, MyCSS_PROPERTY_TYPE_BORDER_TOP_LEFT_RADIUS, mycss_property_parser_border_top_left_radius, 0, 195},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-color", 12, MyCSS_PROPERTY_TYPE_BORDER_COLOR, mycss_property_parser_border_color, 0, 198},
	{"orphans", 7, MyCSS_PROPERTY_TYPE_ORPHANS, mycss_property_parser_orphans, 361, 199},
	{"text-decoration", 15, MyCSS_PROPERTY_TYPE_TEXT_DECORATION, mycss_property_parser_text_decoration, 0, 200},
	{"min-height", 10, MyCSS_PROPERTY_TYPE_MIN_HEIGHT, mycss_property_parser_min_height, 363, 201},
	{"font-language-override", 22, MyCSS_PROPERTY_TYPE_FONT_LANGUAGE_OVERRIDE, mycss_property_parser_font_language_override, 0, 202},
	{"animation-fill-mode", 19, MyCSS_PROPERTY_TYPE_ANIMATION_FILL_MODE, mycss_property_parser_animation_fill_mode, 0, 203},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"column-width", 12, MyCSS_PROPERTY_TYPE_COLUMN_WIDTH, mycss_property_parser_column_width, 364, 206},
	{"background-position", 19, MyCSS_PROPERTY_TYPE_BACKGROUND_POSITION, mycss_property_parser_background_position, 0, 207},
	{"voice-volume", 12, MyCSS_PROPERTY_TYPE_VOICE_VOLUME, mycss_property_parser_voice_volume, 0, 208},
	{"padding-left", 12, MyCSS_PROPERTY_TYPE_PADDING_LEFT, mycss_property_parser_padding_left, 0, 209},
	{"overflow", 8, MyCSS_PROPERTY_TYPE_OVERFLOW, mycss_property_parser_overflow, 365, 210},
	{"text-indent", 11, MyCSS_PROPERTY_TYPE_TEXT_INDENT, mycss_property_parser_text_indent, 367, 211},
	{"box-sizing", 10, MyCSS_PROPERTY_TYPE_BOX_SIZING, mycss_property_parser_box_sizing, 369, 212},
	{"ruby-align", 10, MyCSS_PROPERTY_TYPE_RUBY_ALIGN, mycss_property_parser_ruby_align, 370, 213},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"background-repeat", 17, MyCSS_PROPERTY_TYPE_BACKGROUND_REPEAT, mycss_property_parser_background_repeat, 0, 215},
	{"font-size-adjust", 16, MyCSS_PROPERTY_TYPE_FONT_SIZE_ADJUST, mycss_property_parser_font_size_adjust, 371, 216},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"image-rendering", 15, MyCSS_PROPERTY_TYPE_IMAGE_RENDERING, mycss_property_parser_image_rendering, 372, 218},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"margin-left", 11, MyCSS_PROPERTY_TYPE_MARGIN_LEFT, mycss_property_parser_margin_left, 373, 221},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"contain", 7, MyCSS_PROPERTY_TYPE_CONTAIN, mycss_property_parser_contain, 374, 224},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"padding-bottom", 14, MyCSS_PROPERTY_TYPE_PADDING_BOTTOM, mycss_property_parser_padding_bottom, 0, 226},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"font-variant", 12, MyCSS_PROPERTY_TYPE_FONT_VARIANT, mycss_property_parser_font_variant, 375, 228},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border", 6, MyCSS_PROPERTY_TYPE_BORDER, mycss_property_parser_border, 376, 231},
	{"line-height-step", 16, MyCSS_PROPERTY_TYPE_LINE_HEIGHT_STEP, mycss_property_parser_line_height_step, 0, 232},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"visibility", 10, MyCSS_PROPERTY_TYPE_VISIBILITY, mycss_property_parser_visibility, 377, 235},
	{"font-variant-position", 21, MyCSS_PROPERTY_TYPE_FONT_VARIANT_POSITION, mycss_property_parser_font_variant_position, 379, 236},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"transition-delay", 16, MyCSS_PROPERTY_TYPE_TRANSITION_DELAY, mycss_property_parser_transition_delay, 0, 238},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"font-variant-numeric", 20, MyCSS_PROPERTY_TYPE_FONT_VARIANT_NUMERIC, mycss_property_parser_font_variant_numeric, 380, 240},
	{"margin-right", 12, MyCSS_PROPERTY_TYPE_MARGIN_RIGHT, mycss_property_parser_margin_right, 381, 241},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"min-width", 9, MyCSS_PROPERTY_TYPE_MIN_WIDTH, mycss_property_parser_min_width, 382, 244},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"speak", 5, MyCSS_PROPERTY_TYPE_SPEAK, mycss_property_parser_speak, 383, 247},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"float", 5, MyCSS_PROPERTY_TYPE_FLOAT, mycss_property_parser_float, 0, 249},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"voice-duration", 14, MyCSS_PROPERTY_TYPE_VOICE_DURATION, mycss_property_parser_voice_duration, 384, 251},
	{"font", 4, MyCSS_PROPERTY_TYPE_FONT, mycss_property_parser_font, 386, 252},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"table-layout", 12, MyCSS_PROPERTY_TYPE_TABLE_LAYOUT, mycss_property_parser_table_layout, 0, 254},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"stroke", 6, MyCSS_PROPERTY_TYPE_STROKE, mycss_property_parser_stroke, 0, 259},
	{"line-height", 11, MyCSS_PROPERTY_TYPE_LINE_HEIGHT, mycss_property_parser_line_height, 387, 260},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_TYPE_UNDEF, NULL, 0, 0},
	{"border-bottom", 13, MyCSS_PROPERTY_TYPE_BORDER_BOTTOM, mycss_property_parser_border_bottom, 265, 264},
	{"background-clip", 15, MyCSS_PROPERTY_TYPE_BACKGROUND_CLIP, mycss_property_parser_background_clip, 266, 265},
	{"transition-property", 19, MyCSS_PROPERTY_TYPE_TRANSITION_PROPERTY, mycss_property_parser_transition_property, 0, 266},
	{"text-rendering", 14, MyCSS_PROPERTY_TYPE_TEXT_RENDERING, mycss_property_parser_text_rendering, 0, 267},
	{"pause-after", 11, MyCSS_PROPERTY_TYPE_PAUSE_AFTER, mycss_property_parser_pause_after, 0, 268},
	{"clear-after", 11, MyCSS_PROPERTY_TYPE_CLEAR_AFTER, mycss_property_parser_clear_after, 0, 269},
	{"offset-end", 10, MyCSS_PROPERTY_TYPE_OFFSET_END, mycss_property_parser_offset_end, 0, 270},
	{"pause", 5, MyCSS_PROPERTY_TYPE_PAUSE, mycss_property_parser_pause, 0, 271},
	{"transform-box", 13, MyCSS_PROPERTY_TYPE_TRANSFORM_BOX, mycss_property_parser_transform_box, 0, 272},
	{"text-transform", 14, MyCSS_PROPERTY_TYPE_TEXT_TRANSFORM, mycss_property_parser_text_transform, 274, 273},
	{"border-bottom-style", 19, MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_STYLE, mycss_property_parser_border_bottom_style, 0, 274},
	{"border-bottom-color", 19, MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_COLOR, mycss_property_parser_border_bottom_color, 0, 275},
	{"perspective", 11, MyCSS_PROPERTY_TYPE_PERSPECTIVE, mycss_property_parser_perspective, 277, 276},
	{"shape-outside", 13, MyCSS_PROPERTY_TYPE_SHAPE_OUTSIDE, mycss_property_parser_shape_outside, 0, 277},
	{"fill-opacity", 12, MyCSS_PROPERTY_TYPE_FILL_OPACITY, mycss_property_parser_fill_opacity, 0, 278},
	{"pause-before", 12, MyCSS_PROPERTY_TYPE_PAUSE_BEFORE, mycss_property_parser_pause_before, 0, 279},
	{"rest-after", 10, MyCSS_PROPERTY_TYPE_REST_AFTER, mycss_property_parser_rest_after, 281, 280},
	{"border-left-color", 17, MyCSS_PROPERTY_TYPE_BORDER_LEFT_COLOR, mycss_property_parser_border_left_color, 282, 281},
	{"border-bottom-right-radius", 26, MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_RIGHT_RADIUS, mycss_property_parser_border_bottom_right_radius, 0, 282},
	{"letter-spacing", 14, MyCSS_PROPERTY_TYPE_LETTER_SPACING, mycss_property_parser_letter_spacing, 0, 283},
	{"outline-style", 13, MyCSS_PROPERTY_TYPE_OUTLINE_STYLE, mycss_property_parser_outline_style, 285, 284},
	{"offset-before", 13, MyCSS_PROPERTY_TYPE_OFFSET_BEFORE, mycss_property_parser_offset_before, 0, 285},
	{"background-image", 16, MyCSS_PROPERTY_TYPE_BACKGROUND_IMAGE, mycss_property_parser_background_image, 287, 286},
	{"border-top-style", 16, MyCSS_PROPERTY_TYPE_BORDER_TOP_STYLE, mycss_property_parser_border_top_style, 0, 287},
	{"text-align", 10, MyCSS_PROPERTY_TYPE_TEXT_ALIGN, mycss_property_parser_text_align, 0, 288},
	{"align-content", 13, MyCSS_PROPERTY_TYPE_ALIGN_CONTENT, mycss_property_parser_align_content, 0, 289},
	{"padding-right", 13, MyCSS_PROPERTY_TYPE_PADDING_RIGHT, mycss_property_parser_padding_right, 0, 290},
	{"perspective-origin", 18, MyCSS_PROPERTY_TYPE_PERSPECTIVE_ORIGIN, mycss_property_parser_perspective_origin, 0, 291},
	{"align-self", 10, MyCSS_PROPERTY_TYPE_ALIGN_SELF, mycss_property_parser_align_self, 0, 292},
	{"font-family", 11, MyCSS_PROPERTY_TYPE_FONT_FAMILY, mycss_property_parser_font_family, 294, 293},
	{"touch-action", 12, MyCSS_PROPERTY_TYPE_TOUCH_ACTION, mycss_property_parser_touch_action, 0, 294},
	{"column-rule", 11, MyCSS_PROPERTY_TYPE_COLUMN_RULE, mycss_property_parser_column_rule, 0, 295},
	{"transform-style", 15, MyCSS_PROPERTY_TYPE_TRANSFORM_STYLE, mycss_property_parser_transform_style, 297, 296},
	{"font-variant-caps", 17, MyCSS_PROPERTY_TYPE_FONT_VARIANT_CAPS, mycss_property_parser_font_variant_caps, 0, 297},
	{"font-variant-east-asian", 23, MyCSS_PROPERTY_TYPE_FONT_VARIANT_EAST_ASIAN, mycss_property_parser_font_variant_east_asian, 0, 298},
	{"region-fragment", 15, MyCSS_PROPERTY_TYPE_REGION_FRAGMENT, mycss_property_parser_region_fragment, 0, 299},
	{"string-set", 10, MyCSS_PROPERTY_TYPE_STRING_SET, mycss_property_parser_string_set, 0, 300},
	{"shape-image-threshold", 21, MyCSS_PROPERTY_TYPE_SHAPE_IMAGE_THRESHOLD, mycss_property_parser_shape_image_threshold, 0, 301},
	{"border-image-outset", 19, MyCSS_PROPERTY_TYPE_BORDER_IMAGE_OUTSET, mycss_property_parser_border_image_outset, 303, 302},
	{"border-image-repeat", 19, MyCSS_PROPERTY_TYPE_BORDER_IMAGE_REPEAT, mycss_property_parser_border_image_repeat, 0, 303},
	{"text-combine-upright", 20, MyCSS_PROPERTY_TYPE_TEXT_COMBINE_UPRIGHT, mycss_property_parser_text_combine_upright, 0, 304},
	{"text-orientation", 16, MyCSS_PROPERTY_TYPE_TEXT_ORIENTATION, mycss_property_parser_text_orientation, 306, 305},
	{"transform-origin", 16, MyCSS_PROPERTY_TYPE_TRANSFORM_ORIGIN, mycss_property_parser_transform_origin, 0, 306},
	{"stroke-miterlimit", 17, MyCSS_PROPERTY_TYPE_STROKE_MITERLIMIT, mycss_property_parser_stroke_miterlimit, 308, 307},
	{"stroke-dashoffset", 17, MyCSS_PROPERTY_TYPE_STROKE_DASHOFFSET, mycss_property_parser_stroke_dashoffset, 0, 308},
	{"border-bottom-left-radius", 25, MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_LEFT_RADIUS, mycss_property_parser_border_bottom_left_radius, 0, 309},
	{"column-rule-style", 17, MyCSS_PROPERTY_TYPE_COLUMN_RULE_STYLE, mycss_property_parser_column_rule_style, 0, 310},
	{"hyphens", 7, MyCSS_PROPERTY_TYPE_HYPHENS, mycss_property_parser_hyphens, 312, 311},
	{"text-overflow", 13, MyCSS_PROPERTY_TYPE_TEXT_OVERFLOW, mycss_property_parser_text_overflow, 0, 312},
	{"flex-flow", 9, MyCSS_PROPERTY_TYPE_FLEX_FLOW, mycss_property_parser_flex_flow, 314, 313},
	{"offset-after", 12, MyCSS_PROPERTY_TYPE_OFFSET_AFTER, mycss_property_parser_offset_after, 0, 314},
	{"line-break", 10, MyCSS_PROPERTY_TYPE_LINE_BREAK, mycss_property_parser_line_break, 316, 315},
	{"text-emphasis", 13, MyCSS_PROPERTY_TYPE_TEXT_EMPHASIS, mycss_property_parser_text_emphasis, 0, 316},
	{"float-displace", 14, MyCSS_PROPERTY_TYPE_FLOAT_DISPLACE, mycss_property_parser_float_displace, 0, 317},
	{"bookmark-level", 14, MyCSS_PROPERTY_TYPE_BOOKMARK_LEVEL, mycss_property_parser_bookmark_level, 319, 318},
	{"bookmark-label", 14, MyCSS_PROPERTY_TYPE_BOOKMARK_LABEL, mycss_property_parser_bookmark_label, 0, 319},
	{"animation-delay", 15, MyCSS_PROPERTY_TYPE_ANIMATION_DELAY, mycss_property_parser_animation_delay, 0, 320},
	{"box-decoration-break", 20, MyCSS_PROPERTY_TYPE_BOX_DECORATION_BREAK, mycss_property_parser_box_decoration_break, 0, 321},
	{"text-justify", 12, MyCSS_PROPERTY_TYPE_TEXT_JUSTIFY, mycss_property_parser_text_justify, 0, 322},
	{"border-image-slice", 18, MyCSS_PROPERTY_TYPE_BORDER_IMAGE_SLICE, mycss_property_parser_border_image_slice, 0, 323},
	{"marker-end", 10, MyCSS_PROPERTY_TYPE_MARKER_END, mycss_property_parser_marker_end, 0, 324},
	{"text-align-last", 15, MyCSS_PROPERTY_TYPE_TEXT_ALIGN_LAST, mycss_property_parser_text_align_last, 0, 325},
	{"overflow-x", 10, MyCSS_PROPERTY_TYPE_OVERFLOW_X, mycss_property_parser_overflow_x, 327, 326},
	{"hanging-punctuation", 19, MyCSS_PROPERTY_TYPE_HANGING_PUNCTUATION, mycss_property_parser_hanging_punctuation, 0, 327},
	{"voice-family", 12, MyCSS_PROPERTY_TYPE_VOICE_FAMILY, mycss_property_parser_voice_family, 0, 328},
	{"column-span", 11, MyCSS_PROPERTY_TYPE_COLUMN_SPAN, mycss_property_parser_column_span, 0, 329},
	{"flex-shrink", 11, MyCSS_PROPERTY_TYPE_FLEX_SHRINK, mycss_property_parser_flex_shrink, 0, 330},
	{"outline-color", 13, MyCSS_PROPERTY_TYPE_OUTLINE_COLOR, mycss_property_parser_outline_color, 332, 331},
	{"stroke-linejoin", 15, MyCSS_PROPERTY_TYPE_STROKE_LINEJOIN, mycss_property_parser_stroke_linejoin, 0, 332},
	{"overflow-wrap", 13, MyCSS_PROPERTY_TYPE_OVERFLOW_WRAP, mycss_property_parser_overflow_wrap, 0, 333},
	{"column-rule-color", 17, MyCSS_PROPERTY_TYPE_COLUMN_RULE_COLOR, mycss_property_parser_column_rule_color, 0, 334},
	{"background-size", 15, MyCSS_PROPERTY_TYPE_BACKGROUND_SIZE, mycss_property_parser_background_size, 0, 335},
	{"scroll-padding", 14, MyCSS_PROPERTY_TYPE_SCROLL_PADDING, mycss_property_parser_scroll_padding, 0, 336},
	{"font-size", 9, MyCSS_PROPERTY_TYPE_FONT_SIZE, mycss_property_parser_font_size, 338, 337},
	{"fill-rule", 9, MyCSS_PROPERTY_TYPE_FILL_RULE, mycss_property_parser_fill_rule, 339, 338},
	{"stroke-dasharray", 16, MyCSS_PROPERTY_TYPE_STROKE_DASHARRAY, mycss_property_parser_stroke_dasharray, 0, 339},
	{"border-image-width", 18, MyCSS_PROPERTY_TYPE_BORDER_IMAGE_WIDTH, mycss_property_parser_border_image_width, 0, 340},
	{"clear", 5, MyCSS_PROPERTY_TYPE_CLEAR, mycss_property_parser_clear, 0, 341},
	{"shape-rendering", 15, MyCSS_PROPERTY_TYPE_SHAPE_RENDERING, mycss_property_parser_shape_rendering, 0, 342},
	{"scroll-snap-stop", 16, MyCSS_PROPERTY_TYPE_SCROLL_SNAP_STOP, mycss_property_parser_scroll_snap_stop, 0, 343},
	{"column-gap", 10, MyCSS_PROPERTY_TYPE_COLUMN_GAP, mycss_property_parser_column_gap, 0, 344},
	{"text-size-adjust", 16, MyCSS_PROPERTY_TYPE_TEXT_SIZE_ADJUST, mycss_property_parser_text_size_adjust, 346, 345},
	{"scroll-snap-type", 16, MyCSS_PROPERTY_TYPE_SCROLL_SNAP_TYPE, mycss_property_parser_scroll_snap_type, 347, 346},
	{"font-feature-settings", 21, MyCSS_PROPERTY_TYPE_FONT_FEATURE_SETTINGS, mycss_property_parser_font_feature_settings, 0, 347},
	{"break-inside", 12, MyCSS_PROPERTY_TYPE_BREAK_INSIDE, mycss_property_parser_break_inside, 349, 348},
	{"border-style", 12, MyCSS_PROPERTY_TYPE_BORDER_STYLE, mycss_property_parser_border_style, 350, 349},
	{"border-image", 12, MyCSS_PROPERTY_TYPE_BORDER_IMAGE, mycss_property_parser_border_image, 0, 350},
	{"border-right-color", 18, MyCSS_PROPERTY_TYPE_BORDER_RIGHT_COLOR, mycss_property_parser_border_right_color, 0, 351},
	{"padding-top", 11, MyCSS_PROPERTY_TYPE_PADDING_TOP, mycss_property_parser_padding_top, 0, 352},
	{"content", 7, MyCSS_PROPERTY_TYPE_CONTENT, mycss_property_parser_content, 0, 353},
	{"border-top-color", 16, MyCSS_PROPERTY_TYPE_BORDER_TOP_COLOR, mycss_property_parser_border_top_color, 0, 354},
	{"overflow-y", 10, MyCSS_PROPERTY_TYPE_OVERFLOW_Y, mycss_property_parser_overflow_y, 356, 355},
	{"wrap-through", 12, MyCSS_PROPERTY_TYPE_WRAP_THROUGH, mycss_property_parser_wrap_through, 0, 356},
	{"will-change", 11, MyCSS_PROPERTY_TYPE_WILL_CHANGE, mycss_property_parser_will_change, 358, 357},
	{"white-space", 11, MyCSS_PROPERTY_TYPE_WHITE_SPACE, mycss_property_parser_white_space, 0, 358},
	{"background-attachment", 21, MyCSS_PROPERTY_TYPE_BACKGROUND_ATTACHMENT, mycss_property_parser_background_attachment, 360, 359},
	{"glyph-orientation-vertical", 26, MyCSS_PROPERTY_TYPE_GLYPH_ORIENTATION_VERTICAL, mycss_property_parser_glyph_orientation_vertical, 0, 360},
	{"position", 8, MyCSS_PROPERTY_TYPE_POSITION, mycss_property_parser_position, 362, 361},
	{"list-style", 10, MyCSS_PROPERTY_TYPE_LIST_STYLE, mycss_property_parser_list_style, 0, 362},
	{"max-height", 10, MyCSS_PROPERTY_TYPE_MAX_HEIGHT, mycss_property_parser_max_height, 0, 363},
	{"scroll-snap-margin", 18, MyCSS_PROPERTY_TYPE_SCROLL_SNAP_MARGIN, mycss_property_parser_scroll_snap_margin, 0, 364},
	{"ruby-merge", 10, MyCSS_PROPERTY_TYPE_RUBY_MERGE, mycss_property_parser_ruby_merge, 366, 365},
	{"border-left-style", 17, MyCSS_PROPERTY_TYPE_BORDER_LEFT_STYLE, mycss_property_parser_border_left_style, 0, 366},
	{"empty-cells", 11, MyCSS_PROPERTY_TYPE_EMPTY_CELLS, mycss_property_parser_empty_cells, 368, 367},
	{"border-left-width", 17, MyCSS_PROPERTY_TYPE_BORDER_LEFT_WIDTH, mycss_property_parser_border_left_width, 0, 368},
	{"color-interpolation-filters", 27, MyCSS_PROPERTY_TYPE_COLOR_INTERPOLATION_FILTERS, mycss_property_parser_color_interpolation_filters, 0, 369},
	{"background-origin", 17, MyCSS_PROPERTY_TYPE_BACKGROUND_ORIGIN, mycss_property_parser_background_origin, 0, 370},
	{"font-variant-alternates", 23, MyCSS_PROPERTY_TYPE_FONT_VARIANT_ALTERNATES, mycss_property_parser_font_variant_alternates, 0, 371},
	{"transition-duration", 19, MyCSS_PROPERTY_TYPE_TRANSITION_DURATION, mycss_property_parser_transition_duration, 0, 372},
	{"animation-direction", 19, MyCSS_PROPERTY_TYPE_ANIMATION_DIRECTION, mycss_property_parser_animation_direction, 0, 373},
	{"ruby-position", 13, MyCSS_PROPERTY_TYPE_RUBY_POSITION, mycss_property_parser_ruby_position, 0, 374},
	{"presentation-level", 18, MyCSS_PROPERTY_TYPE_PRESENTATION_LEVEL, mycss_property_parser_presentation_level, 0, 375},
	{"font-weight", 11, MyCSS_PROPERTY_TYPE_FONT_WEIGHT, mycss_property_parser_font_weight, 0, 376},
	{"text-align-all", 14, MyCSS_PROPERTY_TYPE_TEXT_ALIGN_ALL, mycss_property_parser_text_align_all, 378, 377},
	{"bookmark-state", 14, MyCSS_PROPERTY_TYPE_BOOKMARK_STATE, mycss_property_parser_bookmark_state, 0, 378},
	{"text-underline-position", 23, MyCSS_PROPERTY_TYPE_TEXT_UNDERLINE_POSITION, mycss_property_parser_text_underline_position, 0, 379},
	{"text-decoration-color", 21, MyCSS_PROPERTY_TYPE_TEXT_DECORATION_COLOR, mycss_property_parser_text_decoration_color, 0, 380},
	{"marker-start", 12, MyCSS_PROPERTY_TYPE_MARKER_START, mycss_property_parser_marker_start, 0, 381},
	{"max-width", 9, MyCSS_PROPERTY_TYPE_MAX_WIDTH, mycss_property_parser_max_width, 0, 382},
	{"flex-wrap", 9, MyCSS_PROPERTY_TYPE_FLEX_WRAP, mycss_property_parser_flex_wrap, 0, 383},
	{"vertical-align", 14, MyCSS_PROPERTY_TYPE_VERTICAL_ALIGN, mycss_property_parser_vertical_align, 385, 384},
	{"text-decoration-line", 20, MyCSS_PROPERTY_TYPE_TEXT_DECORATION_LINE, mycss_property_parser_text_decoration_line, 0, 385},
	{"max-lines", 9, MyCSS_PROPERTY_TYPE_MAX_LINES, mycss_property_parser_max_lines, 0, 386},
	{"column-count", 12, MyCSS_PROPERTY_TYPE_COLUMN_COUNT, mycss_property_parser_column_count, 388, 387},
	{"color-adjust", 12, MyCSS_PROPERTY_TYPE_COLOR_ADJUST, mycss_property_parser_color_adjust, 389, 388},
	{"text-decoration-skip", 20, MyCSS_PROPERTY_TYPE_TEXT_DECORATION_SKIP, mycss_property_parser_text_decoration_skip, 0, 389},
};

static const mycss_property_value_index_static_entry_t mycss_property_value_index_static_for_search[] = 
{
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"sesame", 6, MyCSS_PROPERTY_VALUE_SESAME, 228, 2},
	{"normal", 6, MyCSS_PROPERTY_VALUE_NORMAL, 0, 3},
	{"contextual", 10, MyCSS_PROPERTY_VALUE_CONTEXTUAL, 229, 4},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"root", 4, MyCSS_PROPERTY_VALUE_ROOT, 0, 6},
	{"isolate", 7, MyCSS_PROPERTY_VALUE_ISOLATE, 0, 7},
	{"view-box", 8, MyCSS_PROPERTY_VALUE_VIEW_BOX, 0, 8},
	{"pan-x", 5, MyCSS_PROPERTY_VALUE_PAN_X, 230, 9},
	{"not-allowed", 11, MyCSS_PROPERTY_VALUE_NOT_ALLOWED, 0, 10},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"avoid-column", 12, MyCSS_PROPERTY_VALUE_AVOID_COLUMN, 233, 13},
	{"reverse", 7, MyCSS_PROPERTY_VALUE_REVERSE, 0, 14},
	{"exact", 5, MyCSS_PROPERTY_VALUE_EXACT, 234, 15},
	{"soft", 4, MyCSS_PROPERTY_VALUE_SOFT, 236, 16},
	{"jis90", 5, MyCSS_PROPERTY_VALUE_JIS90, 0, 17},
	{"jis83", 5, MyCSS_PROPERTY_VALUE_JIS83, 0, 18},
	{"sideways", 8, MyCSS_PROPERTY_VALUE_SIDEWAYS, 238, 19},
	{"100", 3, MyCSS_PROPERTY_VALUE_100, 239, 20},
	{"mixed", 5, MyCSS_PROPERTY_VALUE_MIXED, 242, 21},
	{"hide", 4, MyCSS_PROPERTY_VALUE_HIDE, 0, 22},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"round", 5, MyCSS_PROPERTY_VALUE_ROUND, 243, 24},
	{"90", 2, MyCSS_PROPERTY_VALUE_90, 0, 25},
	{"text", 4, MyCSS_PROPERTY_VALUE_TEXT, 246, 26},
	{"fill", 4, MyCSS_PROPERTY_VALUE_FILL, 247, 27},
	{"0deg", 4, MyCSS_PROPERTY_VALUE_0DEG, 0, 28},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"bevel", 5, MyCSS_PROPERTY_VALUE_BEVEL, 250, 30},
	{"current", 7, MyCSS_PROPERTY_VALUE_CURRENT, 252, 31},
	{"layout", 6, MyCSS_PROPERTY_VALUE_LAYOUT, 254, 32},
	{"petite-caps", 11, MyCSS_PROPERTY_VALUE_PETITE_CAPS, 0, 33},
	{"show", 4, MyCSS_PROPERTY_VALUE_SHOW, 255, 34},
	{"0", 1, MyCSS_PROPERTY_VALUE_0, 0, 35},
	{"open", 4, MyCSS_PROPERTY_VALUE_OPEN, 256, 36},
	{"900", 3, MyCSS_PROPERTY_VALUE_900, 0, 37},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"paint", 5, MyCSS_PROPERTY_VALUE_PAINT, 0, 39},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"x-loud", 6, MyCSS_PROPERTY_VALUE_X_LOUD, 0, 42},
	{"pan-down", 8, MyCSS_PROPERTY_VALUE_PAN_DOWN, 0, 43},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"titling-caps", 12, MyCSS_PROPERTY_VALUE_TITLING_CAPS, 257, 46},
	{"table-header-group", 18, MyCSS_PROPERTY_VALUE_TABLE_HEADER_GROUP, 259, 47},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"line", 4, MyCSS_PROPERTY_VALUE_LINE, 0, 49},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"balance", 7, MyCSS_PROPERTY_VALUE_BALANCE, 261, 52},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"contents", 8, MyCSS_PROPERTY_VALUE_CONTENTS, 262, 54},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"wait", 4, MyCSS_PROPERTY_VALUE_WAIT, 263, 56},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"help", 4, MyCSS_PROPERTY_VALUE_HELP, 264, 58},
	{"600", 3, MyCSS_PROPERTY_VALUE_600, 265, 59},
	{"keep-all", 8, MyCSS_PROPERTY_VALUE_KEEP_ALL, 266, 60},
	{"loose", 5, MyCSS_PROPERTY_VALUE_LOOSE, 267, 61},
	{"absolute", 8, MyCSS_PROPERTY_VALUE_ABSOLUTE, 268, 62},
	{"smaller", 7, MyCSS_PROPERTY_VALUE_SMALLER, 0, 63},
	{"right", 5, MyCSS_PROPERTY_VALUE_RIGHT, 269, 64},
	{"inset", 5, MyCSS_PROPERTY_VALUE_INSET, 270, 65},
	{"row", 3, MyCSS_PROPERTY_VALUE_ROW, 271, 66},
	{"circle", 6, MyCSS_PROPERTY_VALUE_CIRCLE, 0, 67},
	{"bolder", 6, MyCSS_PROPERTY_VALUE_BOLDER, 273, 68},
	{"ruby-text", 9, MyCSS_PROPERTY_VALUE_RUBY_TEXT, 0, 69},
	{"dot", 3, MyCSS_PROPERTY_VALUE_DOT, 274, 70},
	{"loud", 4, MyCSS_PROPERTY_VALUE_LOUD, 276, 71},
	{"full-width", 10, MyCSS_PROPERTY_VALUE_FULL_WIDTH, 0, 72},
	{"butt", 4, MyCSS_PROPERTY_VALUE_BUTT, 279, 73},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"hanging", 7, MyCSS_PROPERTY_VALUE_HANGING, 0, 75},
	{"page", 4, MyCSS_PROPERTY_VALUE_PAGE, 283, 76},
	{"outset", 6, MyCSS_PROPERTY_VALUE_OUTSET, 0, 77},
	{"ellipsis", 8, MyCSS_PROPERTY_VALUE_ELLIPSIS, 284, 78},
	{"bottom", 6, MyCSS_PROPERTY_VALUE_BOTTOM, 286, 79},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"300", 3, MyCSS_PROPERTY_VALUE_300, 288, 81},
	{"fit-content", 11, MyCSS_PROPERTY_VALUE_FIT_CONTENT, 0, 82},
	{"literal-punctuation", 19, MyCSS_PROPERTY_VALUE_LITERAL_PUNCTUATION, 0, 83},
	{"fill-box", 8, MyCSS_PROPERTY_VALUE_FILL_BOX, 289, 84},
	{"weak", 4, MyCSS_PROPERTY_VALUE_WEAK, 290, 85},
	{"minimum", 7, MyCSS_PROPERTY_VALUE_MINIMUM, 293, 86},
	{"hidden", 6, MyCSS_PROPERTY_VALUE_HIDDEN, 0, 87},
	{"clip", 4, MyCSS_PROPERTY_VALUE_CLIP, 294, 88},
	{"collapse", 8, MyCSS_PROPERTY_VALUE_COLLAPSE, 0, 89},
	{"forwards", 8, MyCSS_PROPERTY_VALUE_FORWARDS, 0, 90},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"unicase", 7, MyCSS_PROPERTY_VALUE_UNICASE, 295, 92},
	{"cell", 4, MyCSS_PROPERTY_VALUE_CELL, 296, 93},
	{"jis04", 5, MyCSS_PROPERTY_VALUE_JIS04, 0, 94},
	{"double-circle", 13, MyCSS_PROPERTY_VALUE_DOUBLE_CIRCLE, 298, 95},
	{"stacked-fractions", 17, MyCSS_PROPERTY_VALUE_STACKED_FRACTIONS, 0, 96},
	{"leftwards", 9, MyCSS_PROPERTY_VALUE_LEFTWARDS, 0, 97},
	{"linear", 6, MyCSS_PROPERTY_VALUE_LINEAR, 299, 98},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"x", 1, MyCSS_PROPERTY_VALUE_X, 0, 100},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"x-slow", 6, MyCSS_PROPERTY_VALUE_X_SLOW, 302, 102},
	{"all", 3, MyCSS_PROPERTY_VALUE_ALL, 304, 103},
	{"region", 6, MyCSS_PROPERTY_VALUE_REGION, 306, 104},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"crosshair", 9, MyCSS_PROPERTY_VALUE_CROSSHAIR, 0, 106},
	{"embed", 5, MyCSS_PROPERTY_VALUE_EMBED, 308, 107},
	{"flex-end", 8, MyCSS_PROPERTY_VALUE_FLEX_END, 0, 108},
	{"lowercase", 9, MyCSS_PROPERTY_VALUE_LOWERCASE, 309, 109},
	{"ink", 3, MyCSS_PROPERTY_VALUE_INK, 310, 110},
	{"ne-resize", 9, MyCSS_PROPERTY_VALUE_NE_RESIZE, 311, 111},
	{"isolate-override", 16, MyCSS_PROPERTY_VALUE_ISOLATE_OVERRIDE, 0, 112},
	{"flat", 4, MyCSS_PROPERTY_VALUE_FLAT, 315, 113},
	{"y", 1, MyCSS_PROPERTY_VALUE_Y, 316, 114},
	{"pan-y", 5, MyCSS_PROPERTY_VALUE_PAN_Y, 319, 115},
	{"e-resize", 8, MyCSS_PROPERTY_VALUE_E_RESIZE, 322, 116},
	{"condensed", 9, MyCSS_PROPERTY_VALUE_CONDENSED, 324, 117},
	{"visible", 7, MyCSS_PROPERTY_VALUE_VISIBLE, 325, 118},
	{"upright", 7, MyCSS_PROPERTY_VALUE_UPRIGHT, 329, 119},
	{"800", 3, MyCSS_PROPERTY_VALUE_800, 330, 120},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"repeat", 6, MyCSS_PROPERTY_VALUE_REPEAT, 331, 122},
	{"x-low", 5, MyCSS_PROPERTY_VALUE_X_LOW, 333, 123},
	{"reduced", 7, MyCSS_PROPERTY_VALUE_REDUCED, 334, 124},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"vertical-rl", 11, MyCSS_PROPERTY_VALUE_VERTICAL_RL, 0, 126},
	{"inter-word", 10, MyCSS_PROPERTY_VALUE_INTER_WORD, 0, 127},
	{"pan-up", 6, MyCSS_PROPERTY_VALUE_PAN_UP, 336, 128},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"small", 5, MyCSS_PROPERTY_VALUE_SMALL, 0, 130},
	{"underscore", 10, MyCSS_PROPERTY_VALUE_UNDERSCORE, 337, 131},
	{"on", 2, MyCSS_PROPERTY_VALUE_ON, 338, 132},
	{"allow-end", 9, MyCSS_PROPERTY_VALUE_ALLOW_END, 339, 133},
	{"avoid-page", 10, MyCSS_PROPERTY_VALUE_AVOID_PAGE, 341, 134},
	{"high", 4, MyCSS_PROPERTY_VALUE_HIGH, 342, 135},
	{"both", 4, MyCSS_PROPERTY_VALUE_BOTH, 346, 136},
	{"strict", 6, MyCSS_PROPERTY_VALUE_STRICT, 348, 137},
	{"filled", 6, MyCSS_PROPERTY_VALUE_FILLED, 0, 138},
	{"simplified", 10, MyCSS_PROPERTY_VALUE_SIMPLIFIED, 0, 139},
	{"ridge", 5, MyCSS_PROPERTY_VALUE_RIDGE, 0, 140},
	{"first", 5, MyCSS_PROPERTY_VALUE_FIRST, 351, 141},
	{"500", 3, MyCSS_PROPERTY_VALUE_500, 0, 142},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"off", 3, MyCSS_PROPERTY_VALUE_OFF, 353, 144},
	{"objects", 7, MyCSS_PROPERTY_VALUE_OBJECTS, 0, 145},
	{"nowrap", 6, MyCSS_PROPERTY_VALUE_NOWRAP, 356, 146},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"bar", 3, MyCSS_PROPERTY_VALUE_BAR, 357, 148},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"avoid", 5, MyCSS_PROPERTY_VALUE_AVOID, 0, 150},
	{"pre-line", 8, MyCSS_PROPERTY_VALUE_PRE_LINE, 358, 151},
	{"lighter", 7, MyCSS_PROPERTY_VALUE_LIGHTER, 360, 152},
	{"same", 4, MyCSS_PROPERTY_VALUE_SAME, 361, 153},
	{"closed", 6, MyCSS_PROPERTY_VALUE_CLOSED, 363, 154},
	{"column-reverse", 14, MyCSS_PROPERTY_VALUE_COLUMN_REVERSE, 0, 155},
	{"flex", 4, MyCSS_PROPERTY_VALUE_FLEX, 364, 156},
	{"bold", 4, MyCSS_PROPERTY_VALUE_BOLD, 0, 157},
	{"initial", 7, MyCSS_PROPERTY_VALUE_INITIAL, 0, 158},
	{"inline-list-item", 16, MyCSS_PROPERTY_VALUE_INLINE_LIST_ITEM, 367, 159},
	{"top", 3, MyCSS_PROPERTY_VALUE_TOP, 368, 160},
	{"alias", 5, MyCSS_PROPERTY_VALUE_ALIAS, 369, 161},
	{"default", 7, MyCSS_PROPERTY_VALUE_DEFAULT, 0, 162},
	{"ltr", 3, MyCSS_PROPERTY_VALUE_LTR, 372, 163},
	{"200", 3, MyCSS_PROPERTY_VALUE_200, 375, 164},
	{"menu", 4, MyCSS_PROPERTY_VALUE_MENU, 377, 165},
	{"auto", 4, MyCSS_PROPERTY_VALUE_AUTO, 378, 166},
	{"list-item", 9, MyCSS_PROPERTY_VALUE_LIST_ITEM, 380, 167},
	{"ease-in-out", 11, MyCSS_PROPERTY_VALUE_EASE_IN_OUT, 0, 168},
	{"xx-small", 8, MyCSS_PROPERTY_VALUE_XX_SMALL, 0, 169},
	{"x-large", 7, MyCSS_PROPERTY_VALUE_X_LARGE, 381, 170},
	{"jis78", 5, MyCSS_PROPERTY_VALUE_JIS78, 382, 171},
	{"ease", 4, MyCSS_PROPERTY_VALUE_EASE, 0, 172},
	{"left", 4, MyCSS_PROPERTY_VALUE_LEFT, 385, 173},
	{"line-through", 12, MyCSS_PROPERTY_VALUE_LINE_THROUGH, 0, 174},
	{"super", 5, MyCSS_PROPERTY_VALUE_SUPER, 0, 175},
	{"none", 4, MyCSS_PROPERTY_VALUE_NONE, 387, 176},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"relative", 8, MyCSS_PROPERTY_VALUE_RELATIVE, 0, 178},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"under", 5, MyCSS_PROPERTY_VALUE_UNDER, 0, 180},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"sticky", 6, MyCSS_PROPERTY_VALUE_STICKY, 0, 182},
	{"horizontal", 10, MyCSS_PROPERTY_VALUE_HORIZONTAL, 390, 183},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"stretch", 7, MyCSS_PROPERTY_VALUE_STRETCH, 391, 185},
	{"contain", 7, MyCSS_PROPERTY_VALUE_CONTAIN, 393, 186},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"baseline", 8, MyCSS_PROPERTY_VALUE_BASELINE, 394, 189},
	{"start", 5, MyCSS_PROPERTY_VALUE_START, 395, 190},
	{"edges", 5, MyCSS_PROPERTY_VALUE_EDGES, 398, 191},
	{"column", 6, MyCSS_PROPERTY_VALUE_COLUMN, 0, 192},
	{"always", 6, MyCSS_PROPERTY_VALUE_ALWAYS, 401, 193},
	{"low", 3, MyCSS_PROPERTY_VALUE_LOW, 403, 194},
	{"wrap", 4, MyCSS_PROPERTY_VALUE_WRAP, 0, 195},
	{"economy", 7, MyCSS_PROPERTY_VALUE_ECONOMY, 405, 196},
	{"weight", 6, MyCSS_PROPERTY_VALUE_WEIGHT, 0, 197},
	{"grab", 4, MyCSS_PROPERTY_VALUE_GRAB, 406, 198},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"balance-all", 11, MyCSS_PROPERTY_VALUE_BALANCE_ALL, 0, 201},
	{"flow", 4, MyCSS_PROPERTY_VALUE_FLOW, 409, 202},
	{"700", 3, MyCSS_PROPERTY_VALUE_700, 0, 203},
	{"table-cell", 10, MyCSS_PROPERTY_VALUE_TABLE_CELL, 410, 204},
	{"ease-out", 8, MyCSS_PROPERTY_VALUE_EASE_OUT, 412, 205},
	{"no-repeat", 9, MyCSS_PROPERTY_VALUE_NO_REPEAT, 415, 206},
	{"increment", 9, MyCSS_PROPERTY_VALUE_INCREMENT, 416, 207},
	{"no-drop", 7, MyCSS_PROPERTY_VALUE_NO_DROP, 417, 208},
	{"local", 5, MyCSS_PROPERTY_VALUE_LOCAL, 0, 209},
	{"progress", 8, MyCSS_PROPERTY_VALUE_PROGRESS, 418, 210},
	{"static", 6, MyCSS_PROPERTY_VALUE_STATIC, 0, 211},
	{"x-soft", 6, MyCSS_PROPERTY_VALUE_X_SOFT, 419, 212},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"invert", 6, MyCSS_PROPERTY_VALUE_INVERT, 421, 214},
	{"sub", 3, MyCSS_PROPERTY_VALUE_SUB, 0, 215},
	{"expanded", 8, MyCSS_PROPERTY_VALUE_EXPANDED, 422, 216},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{NULL, 0, MyCSS_PROPERTY_VALUE_UNDEF, 0, 0},
	{"double", 6, MyCSS_PROPERTY_VALUE_DOUBLE, 0, 219},
	{"digits", 6, MyCSS_PROPERTY_VALUE_DIGITS, 0, 220},
	{"block", 5, MyCSS_PROPERTY_VALUE_BLOCK, 423, 221},
	{"all-small-caps", 14, MyCSS_PROPERTY_VALUE_ALL_SMALL_CAPS, 0, 222},
	{"over", 4, MyCSS_PROPERTY_VALUE_OVER, 0, 223},
	{"moderate", 8, MyCSS_PROPERTY_VALUE_MODERATE, 0, 224},
	{"400", 3, MyCSS_PROPERTY_VALUE_400, 427, 225},
	{"move", 4, MyCSS_PROPERTY_VALUE_MOVE, 428, 226},
	{"historical-forms", 16, MyCSS_PROPERTY_VALUE_HISTORICAL_FORMS, 0, 227},
	{"square", 6, MyCSS_PROPERTY_VALUE_SQUARE, 0, 228},
	{"optimizelegibility", 18, MyCSS_PROPERTY_VALUE_OPTIMIZELEGIBILITY, 0, 229},
	{"medium", 6, MyCSS_PROPERTY_VALUE_MEDIUM, 231, 230},
	{"paused", 6, MyCSS_PROPERTY_VALUE_PAUSED, 232, 231},
	{"oldstyle-nums", 13, MyCSS_PROPERTY_VALUE_OLDSTYLE_NUMS, 0, 232},
	{"avoid-region", 12, MyCSS_PROPERTY_VALUE_AVOID_REGION, 0, 233},
	{"table", 5, MyCSS_PROPERTY_VALUE_TABLE, 235, 234},
	{"border-box", 10, MyCSS_PROPERTY_VALUE_BORDER_BOX, 0, 235},
	{"ruby", 4, MyCSS_PROPERTY_VALUE_RUBY, 237, 236},
	{"fragments", 9, MyCSS_PROPERTY_VALUE_FRAGMENTS, 0, 237},
	{"pre-wrap", 8, MyCSS_PROPERTY_VALUE_PRE_WRAP, 0, 238},
	{"copy", 4, MyCSS_PROPERTY_VALUE_COPY, 240, 239},
	{"strong", 6, MyCSS_PROPERTY_VALUE_STRONG, 241, 240},
	{"traditional", 11, MyCSS_PROPERTY_VALUE_TRADITIONAL, 0, 241},
	{"running", 7, MyCSS_PROPERTY_VALUE_RUNNING, 0, 242},
	{"overline", 8, MyCSS_PROPERTY_VALUE_OVERLINE, 244, 243},
	{"plaintext", 9, MyCSS_PROPERTY_VALUE_PLAINTEXT, 245, 244},
	{"pan-right", 9, MyCSS_PROPERTY_VALUE_PAN_RIGHT, 0, 245},
	{"flow-root", 9, MyCSS_PROPERTY_VALUE_FLOW_ROOT, 0, 246},
	{"repeat-x", 8, MyCSS_PROPERTY_VALUE_REPEAT_X, 248, 247},
	{"no-content", 10, MyCSS_PROPERTY_VALUE_NO_CONTENT, 249, 248},
	{"all-petite-caps", 15, MyCSS_PROPERTY_VALUE_ALL_PETITE_CAPS, 0, 249},
	{"vertical", 8, MyCSS_PROPERTY_VALUE_VERTICAL, 251, 250},
	{"ultra-condensed", 15, MyCSS_PROPERTY_VALUE_ULTRA_CONDENSED, 0, 251},
	{"content", 7, MyCSS_PROPERTY_VALUE_CONTENT, 253, 252},
	{"repeat-y", 8, MyCSS_PROPERTY_VALUE_REPEAT_Y, 0, 253},
	{"xx-large", 8, MyCSS_PROPERTY_VALUE_XX_LARGE, 0, 254},
	{"slow", 4, MyCSS_PROPERTY_VALUE_SLOW, 0, 255},
	{"manual", 6, MyCSS_PROPERTY_VALUE_MANUAL, 0, 256},
	{"tabular-nums", 12, MyCSS_PROPERTY_VALUE_TABULAR_NUMS, 258, 257},
	{"discretionary-ligatures", 23, MyCSS_PROPERTY_VALUE_DISCRETIONARY_LIGATURES, 0, 258},
	{"table-footer-group", 18, MyCSS_PROPERTY_VALUE_TABLE_FOOTER_GROUP, 260, 259},
	{"table-column-group", 18, MyCSS_PROPERTY_VALUE_TABLE_COLUMN_GROUP, 0, 260},
	{"row-resize", 10, MyCSS_PROPERTY_VALUE_ROW_RESIZE, 0, 261},
	{"flex-start", 10, MyCSS_PROPERTY_VALUE_FLEX_START, 0, 262},
	{"clone", 5, MyCSS_PROPERTY_VALUE_CLONE, 0, 263},
	{"semi-condensed", 14, MyCSS_PROPERTY_VALUE_SEMI_CONDENSED, 0, 264},
	{"no-punctuation", 14, MyCSS_PROPERTY_VALUE_NO_PUNCTUATION, 0, 265},
	{"block-within-page", 17, MyCSS_PROPERTY_VALUE_BLOCK_WITHIN_PAGE, 0, 266},
	{"large", 5, MyCSS_PROPERTY_VALUE_LARGE, 0, 267},
	{"descendants", 11, MyCSS_PROPERTY_VALUE_DESCENDANTS, 0, 268},
	{"padding-box", 11, MyCSS_PROPERTY_VALUE_PADDING_BOX, 0, 269},
	{"scroll", 6, MyCSS_PROPERTY_VALUE_SCROLL, 0, 270},
	{"step-end", 8, MyCSS_PROPERTY_VALUE_STEP_END, 272, 271},
	{"sideways-lr", 11, MyCSS_PROPERTY_VALUE_SIDEWAYS_LR, 0, 272},
	{"table-row", 9, MyCSS_PROPERTY_VALUE_TABLE_ROW, 0, 273},
	{"solid", 5, MyCSS_PROPERTY_VALUE_SOLID, 275, 274},
	{"proximity", 9, MyCSS_PROPERTY_VALUE_PROXIMITY, 0, 275},
	{"center", 6, MyCSS_PROPERTY_VALUE_CENTER, 277, 276},
	{"inline", 6, MyCSS_PROPERTY_VALUE_INLINE, 278, 277},
	{"inside", 6, MyCSS_PROPERTY_VALUE_INSIDE, 0, 278},
	{"90deg", 5, MyCSS_PROPERTY_VALUE_90DEG, 280, 279},
	{"dotted", 6, MyCSS_PROPERTY_VALUE_DOTTED, 281, 280},
	{"dashed", 6, MyCSS_PROPERTY_VALUE_DASHED, 282, 281},
	{"context-menu", 12, MyCSS_PROPERTY_VALUE_CONTEXT_MENU, 0, 282},
	{"list-container", 14, MyCSS_PROPERTY_VALUE_LIST_CONTAINER, 0, 283},
	{"s-resize", 8, MyCSS_PROPERTY_VALUE_S_RESIZE, 285, 284},
	{"separate", 8, MyCSS_PROPERTY_VALUE_SEPARATE, 0, 285},
	{"complex", 7, MyCSS_PROPERTY_VALUE_COMPLEX, 287, 286},
	{"no-display", 10, MyCSS_PROPERTY_VALUE_NO_DISPLAY, 0, 287},
	{"no-contextual", 13, MyCSS_PROPERTY_VALUE_NO_CONTEXTUAL, 0, 288},
	{"wrap-reverse", 12, MyCSS_PROPERTY_VALUE_WRAP_REVERSE, 0, 289},
	{"discard", 7, MyCSS_PROPERTY_VALUE_DISCARD, 291, 290},
	{"nesw-resize", 11, MyCSS_PROPERTY_VALUE_NESW_RESIZE, 292, 291},
	{"nwse-resize", 11, MyCSS_PROPERTY_VALUE_NWSE_RESIZE, 0, 292},
	{"maximum", 7, MyCSS_PROPERTY_VALUE_MAXIMUM, 0, 293},
	{"x-weak", 6, MyCSS_PROPERTY_VALUE_X_WEAK, 0, 294},
	{"extra-condensed", 15, MyCSS_PROPERTY_VALUE_EXTRA_CONDENSED, 0, 295},
	{"force-end", 9, MyCSS_PROPERTY_VALUE_FORCE_END, 297, 296},
	{"match-parent", 12, MyCSS_PROPERTY_VALUE_MATCH_PARENT, 0, 297},
	{"geometricprecision", 18, MyCSS_PROPERTY_VALUE_GEOMETRICPRECISION, 0, 298},
	{"larger", 6, MyCSS_PROPERTY_VALUE_LARGER, 300, 299},
	{"alternate", 9, MyCSS_PROPERTY_VALUE_ALTERNATE, 301, 300},
	{"available", 9, MyCSS_PROPERTY_VALUE_AVAILABLE, 0, 301},
	{"ew-resize", 9, MyCSS_PROPERTY_VALUE_EW_RESIZE, 303, 302},
	{"each-line", 9, MyCSS_PROPERTY_VALUE_EACH_LINE, 0, 303},
	{"space-between", 13, MyCSS_PROPERTY_VALUE_SPACE_BETWEEN, 305, 304},
	{"small-caption", 13, MyCSS_PROPERTY_VALUE_SMALL_CAPTION, 0, 305},
	{"run-in", 6, MyCSS_PROPERTY_VALUE_RUN_IN, 307, 306},
	{"evenodd", 7, MyCSS_PROPERTY_VALUE_EVENODD, 0, 307},
	{"common-ligatures", 16, MyCSS_PROPERTY_VALUE_COMMON_LIGATURES, 0, 308},
	{"margin-edge", 11, MyCSS_PROPERTY_VALUE_MARGIN_EDGE, 0, 309},
	{"end", 3, MyCSS_PROPERTY_VALUE_END, 0, 310},
	{"nw-resize", 9, MyCSS_PROPERTY_VALUE_NW_RESIZE, 312, 311},
	{"ns-resize", 9, MyCSS_PROPERTY_VALUE_NS_RESIZE, 313, 312},
	{"col-resize", 10, MyCSS_PROPERTY_VALUE_COL_RESIZE, 314, 313},
	{"capitalize", 10, MyCSS_PROPERTY_VALUE_CAPITALIZE, 0, 314},
	{"fast", 4, MyCSS_PROPERTY_VALUE_FAST, 0, 315},
	{"pre", 3, MyCSS_PROPERTY_VALUE_PRE, 317, 316},
	{"grid", 4, MyCSS_PROPERTY_VALUE_GRID, 318, 317},
	{"all-scroll", 10, MyCSS_PROPERTY_VALUE_ALL_SCROLL, 0, 318},
	{"verso", 5, MyCSS_PROPERTY_VALUE_VERSO, 320, 319},
	{"ruby-base", 9, MyCSS_PROPERTY_VALUE_RUBY_BASE, 321, 320},
	{"table-row-group", 15, MyCSS_PROPERTY_VALUE_TABLE_ROW_GROUP, 0, 321},
	{"se-resize", 9, MyCSS_PROPERTY_VALUE_SE_RESIZE, 323, 322},
	{"sw-resize", 9, MyCSS_PROPERTY_VALUE_SW_RESIZE, 0, 323},
	{"optimizequality", 15, MyCSS_PROPERTY_VALUE_OPTIMIZEQUALITY, 0, 324},
	{"justify", 7, MyCSS_PROPERTY_VALUE_JUSTIFY, 326, 325},
	{"overflow", 8, MyCSS_PROPERTY_VALUE_OVERFLOW, 327, 326},
	{"underline", 9, MyCSS_PROPERTY_VALUE_UNDERLINE, 328, 327},
	{"uppercase", 9, MyCSS_PROPERTY_VALUE_UPPERCASE, 0, 328},
	{"nonzero", 7, MyCSS_PROPERTY_VALUE_NONZERO, 0, 329},
	{"icon", 4, MyCSS_PROPERTY_VALUE_ICON, 0, 330},
	{"rightwards", 10, MyCSS_PROPERTY_VALUE_RIGHTWARDS, 332, 331},
	{"status-bar", 10, MyCSS_PROPERTY_VALUE_STATUS_BAR, 0, 332},
	{"table-column", 12, MyCSS_PROPERTY_VALUE_TABLE_COLUMN, 0, 333},
	{"n-resize", 8, MyCSS_PROPERTY_VALUE_N_RESIZE, 335, 334},
	{"crispedges", 10, MyCSS_PROPERTY_VALUE_CRISPEDGES, 0, 335},
	{"spaces", 6, MyCSS_PROPERTY_VALUE_SPACES, 0, 336},
	{"inline-flex", 11, MyCSS_PROPERTY_VALUE_INLINE_FLEX, 0, 337},
	{"w-resize", 8, MyCSS_PROPERTY_VALUE_W_RESIZE, 0, 338},
	{"content-edge", 12, MyCSS_PROPERTY_VALUE_CONTENT_EDGE, 340, 339},
	{"proportional-nums", 17, MyCSS_PROPERTY_VALUE_PROPORTIONAL_NUMS, 0, 340},
	{"ultra-expanded", 14, MyCSS_PROPERTY_VALUE_ULTRA_EXPANDED, 0, 341},
	{"srgb", 4, MyCSS_PROPERTY_VALUE_SRGB, 343, 342},
	{"clear", 5, MyCSS_PROPERTY_VALUE_CLEAR, 344, 343},
	{"cover", 5, MyCSS_PROPERTY_VALUE_COVER, 345, 344},
	{"semi-expanded", 13, MyCSS_PROPERTY_VALUE_SEMI_EXPANDED, 0, 345},
	{"inherit", 7, MyCSS_PROPERTY_VALUE_INHERIT, 347, 346},
	{"x-strong", 8, MyCSS_PROPERTY_VALUE_X_STRONG, 0, 347},
	{"silent", 6, MyCSS_PROPERTY_VALUE_SILENT, 349, 348},
	{"ease-in", 7, MyCSS_PROPERTY_VALUE_EASE_IN, 350, 349},
	{"small-caps", 10, MyCSS_PROPERTY_VALUE_SMALL_CAPS, 0, 350},
	{"currentcolor", 12, MyCSS_PROPERTY_VALUE_CURRENTCOLOR, 352, 351},
	{"inline-table", 12, MyCSS_PROPERTY_VALUE_INLINE_TABLE, 0, 352},
	{"break-all", 9, MyCSS_PROPERTY_VALUE_BREAK_ALL, 354, 353},
	{"linearrgb", 9, MyCSS_PROPERTY_VALUE_LINEARRGB, 355, 354},
	{"proportional-width", 18, MyCSS_PROPERTY_VALUE_PROPORTIONAL_WIDTH, 0, 355},
	{"border-edge", 11, MyCSS_PROPERTY_VALUE_BORDER_EDGE, 0, 356},
	{"x-small", 7, MyCSS_PROPERTY_VALUE_X_SMALL, 0, 357},
	{"preserve", 8, MyCSS_PROPERTY_VALUE_PRESERVE, 359, 358},
	{"paginate", 8, MyCSS_PROPERTY_VALUE_PAGINATE, 0, 359},
	{"step-start", 10, MyCSS_PROPERTY_VALUE_STEP_START, 0, 360},
	{"size", 4, MyCSS_PROPERTY_VALUE_SIZE, 362, 361},
	{"fixed", 5, MyCSS_PROPERTY_VALUE_FIXED, 0, 362},
	{"ordinal", 7, MyCSS_PROPERTY_VALUE_ORDINAL, 0, 363},
	{"content-box", 11, MyCSS_PROPERTY_VALUE_CONTENT_BOX, 365, 364},
	{"horizontal-tb", 13, MyCSS_PROPERTY_VALUE_HORIZONTAL_TB, 366, 365},
	{"optimizespeed", 13, MyCSS_PROPERTY_VALUE_OPTIMIZESPEED, 0, 366},
	{"alternate-reverse", 17, MyCSS_PROPERTY_VALUE_ALTERNATE_REVERSE, 0, 367},
	{"miter", 5, MyCSS_PROPERTY_VALUE_MITER, 0, 368},
	{"min-content", 11, MyCSS_PROPERTY_VALUE_MIN_CONTENT, 370, 369},
	{"max-content", 11, MyCSS_PROPERTY_VALUE_MAX_CONTENT, 371, 370},
	{"text-bottom", 11, MyCSS_PROPERTY_VALUE_TEXT_BOTTOM, 0, 371},
	{"rtl", 3, MyCSS_PROPERTY_VALUE_RTL, 373, 372},
	{"outside", 7, MyCSS_PROPERTY_VALUE_OUTSIDE, 374, 373},
	{"oblique", 7, MyCSS_PROPERTY_VALUE_OBLIQUE, 0, 374},
	{"break-word", 10, MyCSS_PROPERTY_VALUE_BREAK_WORD, 376, 375},
	{"no-historical-ligatures", 23, MyCSS_PROPERTY_VALUE_NO_HISTORICAL_LIGATURES, 0, 376},
	{"recto", 5, MyCSS_PROPERTY_VALUE_RECTO, 0, 377},
	{"wavy", 4, MyCSS_PROPERTY_VALUE_WAVY, 379, 378},
	{"pointer", 7, MyCSS_PROPERTY_VALUE_POINTER, 0, 379},
	{"preserve-3d", 11, MyCSS_PROPERTY_VALUE_PRESERVE_3D, 0, 380},
	{"historical-ligatures", 20, MyCSS_PROPERTY_VALUE_HISTORICAL_LIGATURES, 0, 381},
	{"zoom-out", 8, MyCSS_PROPERTY_VALUE_ZOOM_OUT, 383, 382},
	{"justify-all", 11, MyCSS_PROPERTY_VALUE_JUSTIFY_ALL, 384, 383},
	{"table-caption", 13, MyCSS_PROPERTY_VALUE_TABLE_CAPTION, 0, 384},
	{"last", 4, MyCSS_PROPERTY_VALUE_LAST, 386, 385},
	{"italic", 6, MyCSS_PROPERTY_VALUE_ITALIC, 0, 386},
	{"break-spaces", 12, MyCSS_PROPERTY_VALUE_BREAK_SPACES, 388, 387},
	{"ruby-base-container", 19, MyCSS_PROPERTY_VALUE_RUBY_BASE_CONTAINER, 389, 388},
	{"ruby-text-container", 19, MyCSS_PROPERTY_VALUE_RUBY_TEXT_CONTAINER, 0, 389},
	{"slashed-zero", 12, MyCSS_PROPERTY_VALUE_SLASHED_ZERO, 0, 390},
	{"inline-grid", 11, MyCSS_PROPERTY_VALUE_INLINE_GRID, 392, 391},
	{"no-common-ligatures", 19, MyCSS_PROPERTY_VALUE_NO_COMMON_LIGATURES, 0, 392},
	{"caption", 7, MyCSS_PROPERTY_VALUE_CAPTION, 0, 393},
	{"backwards", 9, MyCSS_PROPERTY_VALUE_BACKWARDS, 0, 394},
	{"zoom-in", 7, MyCSS_PROPERTY_VALUE_ZOOM_IN, 396, 395},
	{"message-box", 11, MyCSS_PROPERTY_VALUE_MESSAGE_BOX, 397, 396},
	{"manipulation", 12, MyCSS_PROPERTY_VALUE_MANIPULATION, 0, 397},
	{"style", 5, MyCSS_PROPERTY_VALUE_STYLE, 399, 398},
	{"slice", 5, MyCSS_PROPERTY_VALUE_SLICE, 400, 399},
	{"space", 5, MyCSS_PROPERTY_VALUE_SPACE, 0, 400},
	{"bidi-override", 13, MyCSS_PROPERTY_VALUE_BIDI_OVERRIDE, 402, 401},
	{"box-decoration", 14, MyCSS_PROPERTY_VALUE_BOX_DECORATION, 0, 402},
	{"sideways-rl", 11, MyCSS_PROPERTY_VALUE_SIDEWAYS_RL, 404, 403},
	{"lining-nums", 11, MyCSS_PROPERTY_VALUE_LINING_NUMS, 0, 404},
	{"vertical-lr", 11, MyCSS_PROPERTY_VALUE_VERTICAL_LR, 0, 405},
	{"x-high", 6, MyCSS_PROPERTY_VALUE_X_HIGH, 407, 406},
	{"pan-left", 8, MyCSS_PROPERTY_VALUE_PAN_LEFT, 408, 407},
	{"text-top", 8, MyCSS_PROPERTY_VALUE_TEXT_TOP, 0, 408},
	{"grabbing", 8, MyCSS_PROPERTY_VALUE_GRABBING, 0, 409},
	{"vertical-text", 13, MyCSS_PROPERTY_VALUE_VERTICAL_TEXT, 411, 410},
	{"diagonal-fractions", 18, MyCSS_PROPERTY_VALUE_DIAGONAL_FRACTIONS, 0, 411},
	{"triangle", 8, MyCSS_PROPERTY_VALUE_TRIANGLE, 413, 412},
	{"spell-out", 9, MyCSS_PROPERTY_VALUE_SPELL_OUT, 414, 413},
	{"no-discretionary-ligatures", 26, MyCSS_PROPERTY_VALUE_NO_DISCRETIONARY_LIGATURES, 0, 414},
	{"scroll-position", 15, MyCSS_PROPERTY_VALUE_SCROLL_POSITION, 0, 415},
	{"extra-expanded", 14, MyCSS_PROPERTY_VALUE_EXTRA_EXPANDED, 0, 416},
	{"mandatory", 9, MyCSS_PROPERTY_VALUE_MANDATORY, 0, 417},
	{"inline-block", 12, MyCSS_PROPERTY_VALUE_INLINE_BLOCK, 0, 418},
	{"x-fast", 6, MyCSS_PROPERTY_VALUE_X_FAST, 420, 419},
	{"space-around", 12, MyCSS_PROPERTY_VALUE_SPACE_AROUND, 0, 420},
	{"indent", 6, MyCSS_PROPERTY_VALUE_INDENT, 0, 421},
	{"row-reverse", 11, MyCSS_PROPERTY_VALUE_ROW_REVERSE, 0, 422},
	{"blink", 5, MyCSS_PROPERTY_VALUE_BLINK, 424, 423},
	{"break", 5, MyCSS_PROPERTY_VALUE_BREAK, 425, 424},
	{"groove", 6, MyCSS_PROPERTY_VALUE_GROOVE, 426, 425},
	{"inter-character", 15, MyCSS_PROPERTY_VALUE_INTER_CHARACTER, 0, 426},
	{"middle", 6, MyCSS_PROPERTY_VALUE_MIDDLE, 0, 427},
	{"padding-edge", 12, MyCSS_PROPERTY_VALUE_PADDING_EDGE, 0, 428},
};


#endif /* MyHTML_MyCSS_PROPERTY_RESOURCES_H */
