/*
 Copyright (C) 2015-2016 Alexander Borisov

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

 Author: lex.borisov@gmail.com (Alexander Borisov)
*/

#ifndef MyHTML_MyCSS_PROPERTY_CONST_H
#define MyHTML_MyCSS_PROPERTY_CONST_H
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

enum mycss_property_type {
	MyCSS_PROPERTY_TYPE_UNDEF                      = 0x0000,
	MyCSS_PROPERTY_TYPE_ALIGN_CONTENT              = 0x0001,
	MyCSS_PROPERTY_TYPE_ALIGN_ITEMS                = 0x0002,
	MyCSS_PROPERTY_TYPE_ALIGN_SELF                 = 0x0003,
	MyCSS_PROPERTY_TYPE_BACKGROUND                 = 0x0004,
	MyCSS_PROPERTY_TYPE_BACKGROUND_ATTACHMENT      = 0x0005,
	MyCSS_PROPERTY_TYPE_BACKGROUND_CLIP            = 0x0006,
	MyCSS_PROPERTY_TYPE_BACKGROUND_COLOR           = 0x0007,
	MyCSS_PROPERTY_TYPE_BACKGROUND_IMAGE           = 0x0008,
	MyCSS_PROPERTY_TYPE_BACKGROUND_ORIGIN          = 0x0009,
	MyCSS_PROPERTY_TYPE_BACKGROUND_POSITION        = 0x000a,
	MyCSS_PROPERTY_TYPE_BACKGROUND_REPEAT          = 0x000b,
	MyCSS_PROPERTY_TYPE_BACKGROUND_SIZE            = 0x000c,
	MyCSS_PROPERTY_TYPE_BORDER                     = 0x000d,
	MyCSS_PROPERTY_TYPE_BORDER_BOTTOM              = 0x000e,
	MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_COLOR        = 0x000f,
	MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_LEFT_RADIUS  = 0x0010,
	MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_RIGHT_RADIUS = 0x0011,
	MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_STYLE        = 0x0012,
	MyCSS_PROPERTY_TYPE_BORDER_BOTTOM_WIDTH        = 0x0013,
	MyCSS_PROPERTY_TYPE_BORDER_COLOR               = 0x0014,
	MyCSS_PROPERTY_TYPE_BORDER_IMAGE               = 0x0015,
	MyCSS_PROPERTY_TYPE_BORDER_IMAGE_OUTSET        = 0x0016,
	MyCSS_PROPERTY_TYPE_BORDER_IMAGE_REPEAT        = 0x0017,
	MyCSS_PROPERTY_TYPE_BORDER_IMAGE_SLICE         = 0x0018,
	MyCSS_PROPERTY_TYPE_BORDER_IMAGE_WIDTH         = 0x0019,
	MyCSS_PROPERTY_TYPE_BORDER_LEFT                = 0x001a,
	MyCSS_PROPERTY_TYPE_BORDER_LEFT_COLOR          = 0x001b,
	MyCSS_PROPERTY_TYPE_BORDER_LEFT_STYLE          = 0x001c,
	MyCSS_PROPERTY_TYPE_BORDER_LEFT_WIDTH          = 0x001d,
	MyCSS_PROPERTY_TYPE_BORDER_RADIUS              = 0x001e,
	MyCSS_PROPERTY_TYPE_BORDER_RIGHT               = 0x001f,
	MyCSS_PROPERTY_TYPE_BORDER_RIGHT_COLOR         = 0x0020,
	MyCSS_PROPERTY_TYPE_BORDER_RIGHT_STYLE         = 0x0021,
	MyCSS_PROPERTY_TYPE_BORDER_RIGHT_WIDTH         = 0x0022,
	MyCSS_PROPERTY_TYPE_BORDER_STYLE               = 0x0023,
	MyCSS_PROPERTY_TYPE_BORDER_TOP                 = 0x0024,
	MyCSS_PROPERTY_TYPE_BORDER_TOP_COLOR           = 0x0025,
	MyCSS_PROPERTY_TYPE_BORDER_TOP_LEFT_RADIUS     = 0x0026,
	MyCSS_PROPERTY_TYPE_BORDER_TOP_RIGHT_RADIUS    = 0x0027,
	MyCSS_PROPERTY_TYPE_BORDER_TOP_STYLE           = 0x0028,
	MyCSS_PROPERTY_TYPE_BORDER_TOP_WIDTH           = 0x0029,
	MyCSS_PROPERTY_TYPE_BORDER_WIDTH               = 0x002a,
	MyCSS_PROPERTY_TYPE_BOX_SHADOW                 = 0x002b,
	MyCSS_PROPERTY_TYPE_BOX_SUPPRESS               = 0x002c,
	MyCSS_PROPERTY_TYPE_CLEAR                      = 0x002d,
	MyCSS_PROPERTY_TYPE_CLEAR_AFTER                = 0x002e,
	MyCSS_PROPERTY_TYPE_DISPLAY                    = 0x002f,
	MyCSS_PROPERTY_TYPE_FLEX                       = 0x0030,
	MyCSS_PROPERTY_TYPE_FLEX_BASIS                 = 0x0031,
	MyCSS_PROPERTY_TYPE_FLEX_DIRECTION             = 0x0032,
	MyCSS_PROPERTY_TYPE_FLEX_FLOW                  = 0x0033,
	MyCSS_PROPERTY_TYPE_FLEX_GROW                  = 0x0034,
	MyCSS_PROPERTY_TYPE_FLEX_SHRINK                = 0x0035,
	MyCSS_PROPERTY_TYPE_FLEX_WRAP                  = 0x0036,
	MyCSS_PROPERTY_TYPE_FLOAT                      = 0x0037,
	MyCSS_PROPERTY_TYPE_FLOAT_DISPLACE             = 0x0038,
	MyCSS_PROPERTY_TYPE_FONT                       = 0x0039,
	MyCSS_PROPERTY_TYPE_FONT_FAMILY                = 0x003a,
	MyCSS_PROPERTY_TYPE_FONT_FEATURE_SETTINGS      = 0x003b,
	MyCSS_PROPERTY_TYPE_FONT_KERNING               = 0x003c,
	MyCSS_PROPERTY_TYPE_FONT_LANGUAGE_OVERRIDE     = 0x003d,
	MyCSS_PROPERTY_TYPE_FONT_SIZE                  = 0x003e,
	MyCSS_PROPERTY_TYPE_FONT_SIZE_ADJUST           = 0x003f,
	MyCSS_PROPERTY_TYPE_FONT_STRETCH               = 0x0040,
	MyCSS_PROPERTY_TYPE_FONT_STYLE                 = 0x0041,
	MyCSS_PROPERTY_TYPE_FONT_SYNTHESIS             = 0x0042,
	MyCSS_PROPERTY_TYPE_FONT_VARIANT               = 0x0043,
	MyCSS_PROPERTY_TYPE_FONT_VARIANT_ALTERNATES    = 0x0044,
	MyCSS_PROPERTY_TYPE_FONT_VARIANT_CAPS          = 0x0045,
	MyCSS_PROPERTY_TYPE_FONT_VARIANT_EAST_ASIAN    = 0x0046,
	MyCSS_PROPERTY_TYPE_FONT_VARIANT_LIGATURES     = 0x0047,
	MyCSS_PROPERTY_TYPE_FONT_VARIANT_NUMERIC       = 0x0048,
	MyCSS_PROPERTY_TYPE_FONT_VARIANT_POSITION      = 0x0049,
	MyCSS_PROPERTY_TYPE_FONT_WEIGHT                = 0x004a,
	MyCSS_PROPERTY_TYPE_HEIGHT                     = 0x004b,
	MyCSS_PROPERTY_TYPE_INDENT_EDGE_RESET          = 0x004c,
	MyCSS_PROPERTY_TYPE_JUSTIFY_CONTENT            = 0x004d,
	MyCSS_PROPERTY_TYPE_MARGIN                     = 0x004e,
	MyCSS_PROPERTY_TYPE_MARGIN_BOTTOM              = 0x004f,
	MyCSS_PROPERTY_TYPE_MARGIN_LEFT                = 0x0050,
	MyCSS_PROPERTY_TYPE_MARGIN_RIGHT               = 0x0051,
	MyCSS_PROPERTY_TYPE_MARGIN_TOP                 = 0x0052,
	MyCSS_PROPERTY_TYPE_MAX_HEIGHT                 = 0x0053,
	MyCSS_PROPERTY_TYPE_MAX_WIDTH                  = 0x0054,
	MyCSS_PROPERTY_TYPE_MIN_HEIGHT                 = 0x0055,
	MyCSS_PROPERTY_TYPE_MIN_WIDTH                  = 0x0056,
	MyCSS_PROPERTY_TYPE_ORDER                      = 0x0057,
	MyCSS_PROPERTY_TYPE_OVERFLOW                   = 0x0058,
	MyCSS_PROPERTY_TYPE_OVERFLOW_X                 = 0x0059,
	MyCSS_PROPERTY_TYPE_OVERFLOW_Y                 = 0x005a,
	MyCSS_PROPERTY_TYPE_PADDING                    = 0x005b,
	MyCSS_PROPERTY_TYPE_PADDING_BOTTOM             = 0x005c,
	MyCSS_PROPERTY_TYPE_PADDING_LEFT               = 0x005d,
	MyCSS_PROPERTY_TYPE_PADDING_RIGHT              = 0x005e,
	MyCSS_PROPERTY_TYPE_PADDING_TOP                = 0x005f,
	MyCSS_PROPERTY_TYPE_VISIBILITY                 = 0x0060,
	MyCSS_PROPERTY_TYPE_WIDTH                      = 0x0061,
	MyCSS_PROPERTY_TYPE_LAST_ENTRY                 = 0x0062
}
typedef mycss_property_type_t;

enum mycss_property_value {
	MyCSS_PROPERTY_VALUE_UNDEF                      = 0x0000,
	MyCSS_PROPERTY_VALUE_100                        = 0x0001,
	MyCSS_PROPERTY_VALUE_200                        = 0x0002,
	MyCSS_PROPERTY_VALUE_300                        = 0x0003,
	MyCSS_PROPERTY_VALUE_400                        = 0x0004,
	MyCSS_PROPERTY_VALUE_500                        = 0x0005,
	MyCSS_PROPERTY_VALUE_600                        = 0x0006,
	MyCSS_PROPERTY_VALUE_700                        = 0x0007,
	MyCSS_PROPERTY_VALUE_800                        = 0x0008,
	MyCSS_PROPERTY_VALUE_900                        = 0x0009,
	MyCSS_PROPERTY_VALUE_ALL_PETITE_CAPS            = 0x000a,
	MyCSS_PROPERTY_VALUE_ALL_SMALL_CAPS             = 0x000b,
	MyCSS_PROPERTY_VALUE_AUTO                       = 0x000c,
	MyCSS_PROPERTY_VALUE_AVAILABLE                  = 0x000d,
	MyCSS_PROPERTY_VALUE_BASELINE                   = 0x000e,
	MyCSS_PROPERTY_VALUE_BLOCK                      = 0x000f,
	MyCSS_PROPERTY_VALUE_BLOCK_WITHIN_PAGE          = 0x0010,
	MyCSS_PROPERTY_VALUE_BOLD                       = 0x0011,
	MyCSS_PROPERTY_VALUE_BOLDER                     = 0x0012,
	MyCSS_PROPERTY_VALUE_BORDER_BOX                 = 0x0013,
	MyCSS_PROPERTY_VALUE_BORDER_EDGE                = 0x0014,
	MyCSS_PROPERTY_VALUE_BOTH                       = 0x0015,
	MyCSS_PROPERTY_VALUE_BOTTOM                     = 0x0016,
	MyCSS_PROPERTY_VALUE_CAPTION                    = 0x0017,
	MyCSS_PROPERTY_VALUE_CENTER                     = 0x0018,
	MyCSS_PROPERTY_VALUE_COLLAPSE                   = 0x0019,
	MyCSS_PROPERTY_VALUE_COLUMN                     = 0x001a,
	MyCSS_PROPERTY_VALUE_COLUMN_REVERSE             = 0x001b,
	MyCSS_PROPERTY_VALUE_COMMON_LIGATURES           = 0x001c,
	MyCSS_PROPERTY_VALUE_COMPLEX                    = 0x001d,
	MyCSS_PROPERTY_VALUE_CONDENSED                  = 0x001e,
	MyCSS_PROPERTY_VALUE_CONTAIN                    = 0x001f,
	MyCSS_PROPERTY_VALUE_CONTENT                    = 0x0020,
	MyCSS_PROPERTY_VALUE_CONTENT_BOX                = 0x0021,
	MyCSS_PROPERTY_VALUE_CONTENT_EDGE               = 0x0022,
	MyCSS_PROPERTY_VALUE_CONTENTS                   = 0x0023,
	MyCSS_PROPERTY_VALUE_CONTEXTUAL                 = 0x0024,
	MyCSS_PROPERTY_VALUE_COVER                      = 0x0025,
	MyCSS_PROPERTY_VALUE_DASHED                     = 0x0026,
	MyCSS_PROPERTY_VALUE_DESCENDANTS                = 0x0027,
	MyCSS_PROPERTY_VALUE_DIAGONAL_FRACTIONS         = 0x0028,
	MyCSS_PROPERTY_VALUE_DISCARD                    = 0x0029,
	MyCSS_PROPERTY_VALUE_DISCRETIONARY_LIGATURES    = 0x002a,
	MyCSS_PROPERTY_VALUE_DOTTED                     = 0x002b,
	MyCSS_PROPERTY_VALUE_DOUBLE                     = 0x002c,
	MyCSS_PROPERTY_VALUE_END                        = 0x002d,
	MyCSS_PROPERTY_VALUE_EXPANDED                   = 0x002e,
	MyCSS_PROPERTY_VALUE_EXTRA_CONDENSED            = 0x002f,
	MyCSS_PROPERTY_VALUE_EXTRA_EXPANDED             = 0x0030,
	MyCSS_PROPERTY_VALUE_FILL                       = 0x0031,
	MyCSS_PROPERTY_VALUE_FIT_CONTENT                = 0x0032,
	MyCSS_PROPERTY_VALUE_FIXED                      = 0x0033,
	MyCSS_PROPERTY_VALUE_FLEX                       = 0x0034,
	MyCSS_PROPERTY_VALUE_FLEX_END                   = 0x0035,
	MyCSS_PROPERTY_VALUE_FLEX_START                 = 0x0036,
	MyCSS_PROPERTY_VALUE_FLOW                       = 0x0037,
	MyCSS_PROPERTY_VALUE_FLOW_ROOT                  = 0x0038,
	MyCSS_PROPERTY_VALUE_FULL_WIDTH                 = 0x0039,
	MyCSS_PROPERTY_VALUE_GRID                       = 0x003a,
	MyCSS_PROPERTY_VALUE_GROOVE                     = 0x003b,
	MyCSS_PROPERTY_VALUE_HIDDEN                     = 0x003c,
	MyCSS_PROPERTY_VALUE_HIDE                       = 0x003d,
	MyCSS_PROPERTY_VALUE_HISTORICAL_FORMS           = 0x003e,
	MyCSS_PROPERTY_VALUE_HISTORICAL_LIGATURES       = 0x003f,
	MyCSS_PROPERTY_VALUE_ICON                       = 0x0040,
	MyCSS_PROPERTY_VALUE_INDENT                     = 0x0041,
	MyCSS_PROPERTY_VALUE_INHERIT                    = 0x0042,
	MyCSS_PROPERTY_VALUE_INLINE                     = 0x0043,
	MyCSS_PROPERTY_VALUE_INLINE_BLOCK               = 0x0044,
	MyCSS_PROPERTY_VALUE_INLINE_FLEX                = 0x0045,
	MyCSS_PROPERTY_VALUE_INLINE_GRID                = 0x0046,
	MyCSS_PROPERTY_VALUE_INLINE_LIST_ITEM           = 0x0047,
	MyCSS_PROPERTY_VALUE_INLINE_TABLE               = 0x0048,
	MyCSS_PROPERTY_VALUE_INSET                      = 0x0049,
	MyCSS_PROPERTY_VALUE_INSIDE                     = 0x004a,
	MyCSS_PROPERTY_VALUE_ITALIC                     = 0x004b,
	MyCSS_PROPERTY_VALUE_JIS04                      = 0x004c,
	MyCSS_PROPERTY_VALUE_JIS78                      = 0x004d,
	MyCSS_PROPERTY_VALUE_JIS83                      = 0x004e,
	MyCSS_PROPERTY_VALUE_JIS90                      = 0x004f,
	MyCSS_PROPERTY_VALUE_LARGE                      = 0x0050,
	MyCSS_PROPERTY_VALUE_LARGER                     = 0x0051,
	MyCSS_PROPERTY_VALUE_LEFT                       = 0x0052,
	MyCSS_PROPERTY_VALUE_LENGTH                     = 0x0053,
	MyCSS_PROPERTY_VALUE_LIGHTER                    = 0x0054,
	MyCSS_PROPERTY_VALUE_LINE                       = 0x0055,
	MyCSS_PROPERTY_VALUE_LINING_NUMS                = 0x0056,
	MyCSS_PROPERTY_VALUE_LIST_ITEM                  = 0x0057,
	MyCSS_PROPERTY_VALUE_LOCAL                      = 0x0058,
	MyCSS_PROPERTY_VALUE_MARGIN_EDGE                = 0x0059,
	MyCSS_PROPERTY_VALUE_MAX_CONTENT                = 0x005a,
	MyCSS_PROPERTY_VALUE_MEDIUM                     = 0x005b,
	MyCSS_PROPERTY_VALUE_MENU                       = 0x005c,
	MyCSS_PROPERTY_VALUE_MESSAGE_BOX                = 0x005d,
	MyCSS_PROPERTY_VALUE_MIN_CONTENT                = 0x005e,
	MyCSS_PROPERTY_VALUE_NO_COMMON_LIGATURES        = 0x005f,
	MyCSS_PROPERTY_VALUE_NO_CONTENT                 = 0x0060,
	MyCSS_PROPERTY_VALUE_NO_CONTEXTUAL              = 0x0061,
	MyCSS_PROPERTY_VALUE_NO_DISCRETIONARY_LIGATURES = 0x0062,
	MyCSS_PROPERTY_VALUE_NO_DISPLAY                 = 0x0063,
	MyCSS_PROPERTY_VALUE_NO_HISTORICAL_LIGATURES    = 0x0064,
	MyCSS_PROPERTY_VALUE_NO_REPEAT                  = 0x0065,
	MyCSS_PROPERTY_VALUE_NONE                       = 0x0066,
	MyCSS_PROPERTY_VALUE_NORMAL                     = 0x0067,
	MyCSS_PROPERTY_VALUE_NOWRAP                     = 0x0068,
	MyCSS_PROPERTY_VALUE_OBLIQUE                    = 0x0069,
	MyCSS_PROPERTY_VALUE_OFF                        = 0x006a,
	MyCSS_PROPERTY_VALUE_OLDSTYLE_NUMS              = 0x006b,
	MyCSS_PROPERTY_VALUE_ON                         = 0x006c,
	MyCSS_PROPERTY_VALUE_ORDINAL                    = 0x006d,
	MyCSS_PROPERTY_VALUE_OUTSET                     = 0x006e,
	MyCSS_PROPERTY_VALUE_OUTSIDE                    = 0x006f,
	MyCSS_PROPERTY_VALUE_PADDING_BOX                = 0x0070,
	MyCSS_PROPERTY_VALUE_PADDING_EDGE               = 0x0071,
	MyCSS_PROPERTY_VALUE_PERCENTAGE                 = 0x0072,
	MyCSS_PROPERTY_VALUE_PETITE_CAPS                = 0x0073,
	MyCSS_PROPERTY_VALUE_PROPORTIONAL_NUMS          = 0x0074,
	MyCSS_PROPERTY_VALUE_PROPORTIONAL_WIDTH         = 0x0075,
	MyCSS_PROPERTY_VALUE_REPEAT                     = 0x0076,
	MyCSS_PROPERTY_VALUE_REPEAT_X                   = 0x0077,
	MyCSS_PROPERTY_VALUE_REPEAT_Y                   = 0x0078,
	MyCSS_PROPERTY_VALUE_RIDGE                      = 0x0079,
	MyCSS_PROPERTY_VALUE_RIGHT                      = 0x007a,
	MyCSS_PROPERTY_VALUE_ROUND                      = 0x007b,
	MyCSS_PROPERTY_VALUE_ROW                        = 0x007c,
	MyCSS_PROPERTY_VALUE_ROW_REVERSE                = 0x007d,
	MyCSS_PROPERTY_VALUE_RUBY                       = 0x007e,
	MyCSS_PROPERTY_VALUE_RUBY_BASE                  = 0x007f,
	MyCSS_PROPERTY_VALUE_RUBY_BASE_CONTAINER        = 0x0080,
	MyCSS_PROPERTY_VALUE_RUBY_TEXT                  = 0x0081,
	MyCSS_PROPERTY_VALUE_RUBY_TEXT_CONTAINER        = 0x0082,
	MyCSS_PROPERTY_VALUE_RUN_IN                     = 0x0083,
	MyCSS_PROPERTY_VALUE_SCROLL                     = 0x0084,
	MyCSS_PROPERTY_VALUE_SEMI_CONDENSED             = 0x0085,
	MyCSS_PROPERTY_VALUE_SEMI_EXPANDED              = 0x0086,
	MyCSS_PROPERTY_VALUE_SHOW                       = 0x0087,
	MyCSS_PROPERTY_VALUE_SIMPLIFIED                 = 0x0088,
	MyCSS_PROPERTY_VALUE_SLASHED_ZERO               = 0x0089,
	MyCSS_PROPERTY_VALUE_SMALL                      = 0x008a,
	MyCSS_PROPERTY_VALUE_SMALL_CAPS                 = 0x008b,
	MyCSS_PROPERTY_VALUE_SMALL_CAPTION              = 0x008c,
	MyCSS_PROPERTY_VALUE_SMALLER                    = 0x008d,
	MyCSS_PROPERTY_VALUE_SOLID                      = 0x008e,
	MyCSS_PROPERTY_VALUE_SPACE                      = 0x008f,
	MyCSS_PROPERTY_VALUE_SPACE_AROUND               = 0x0090,
	MyCSS_PROPERTY_VALUE_SPACE_BETWEEN              = 0x0091,
	MyCSS_PROPERTY_VALUE_STACKED_FRACTIONS          = 0x0092,
	MyCSS_PROPERTY_VALUE_START                      = 0x0093,
	MyCSS_PROPERTY_VALUE_STATUS_BAR                 = 0x0094,
	MyCSS_PROPERTY_VALUE_STRETCH                    = 0x0095,
	MyCSS_PROPERTY_VALUE_STYLE                      = 0x0096,
	MyCSS_PROPERTY_VALUE_SUB                        = 0x0097,
	MyCSS_PROPERTY_VALUE_SUPER                      = 0x0098,
	MyCSS_PROPERTY_VALUE_TABLE                      = 0x0099,
	MyCSS_PROPERTY_VALUE_TABLE_CAPTION              = 0x009a,
	MyCSS_PROPERTY_VALUE_TABLE_CELL                 = 0x009b,
	MyCSS_PROPERTY_VALUE_TABLE_COLUMN               = 0x009c,
	MyCSS_PROPERTY_VALUE_TABLE_COLUMN_GROUP         = 0x009d,
	MyCSS_PROPERTY_VALUE_TABLE_FOOTER_GROUP         = 0x009e,
	MyCSS_PROPERTY_VALUE_TABLE_HEADER_GROUP         = 0x009f,
	MyCSS_PROPERTY_VALUE_TABLE_ROW                  = 0x00a0,
	MyCSS_PROPERTY_VALUE_TABLE_ROW_GROUP            = 0x00a1,
	MyCSS_PROPERTY_VALUE_TABULAR_NUMS               = 0x00a2,
	MyCSS_PROPERTY_VALUE_TITLING_CAPS               = 0x00a3,
	MyCSS_PROPERTY_VALUE_TOP                        = 0x00a4,
	MyCSS_PROPERTY_VALUE_TRADITIONAL                = 0x00a5,
	MyCSS_PROPERTY_VALUE_ULTRA_CONDENSED            = 0x00a6,
	MyCSS_PROPERTY_VALUE_ULTRA_EXPANDED             = 0x00a7,
	MyCSS_PROPERTY_VALUE_UNICASE                    = 0x00a8,
	MyCSS_PROPERTY_VALUE_VISIBLE                    = 0x00a9,
	MyCSS_PROPERTY_VALUE_WEIGHT                     = 0x00aa,
	MyCSS_PROPERTY_VALUE_WRAP                       = 0x00ab,
	MyCSS_PROPERTY_VALUE_WRAP_REVERSE               = 0x00ac,
	MyCSS_PROPERTY_VALUE_X_LARGE                    = 0x00ad,
	MyCSS_PROPERTY_VALUE_X_SMALL                    = 0x00ae,
	MyCSS_PROPERTY_VALUE_XX_LARGE                   = 0x00af,
	MyCSS_PROPERTY_VALUE_XX_SMALL                   = 0x00b0,
	MyCSS_PROPERTY_VALUE_LAST_ENTRY                 = 0x00b1
}
typedef mycss_property_value_t;

enum mycss_property_align_content {
	MyCSS_PROPERTY_ALIGN_CONTENT_CENTER        = 0x0018,
	MyCSS_PROPERTY_ALIGN_CONTENT_FLEX_END      = 0x0035,
	MyCSS_PROPERTY_ALIGN_CONTENT_FLEX_START    = 0x0036,
	MyCSS_PROPERTY_ALIGN_CONTENT_SPACE_AROUND  = 0x0090,
	MyCSS_PROPERTY_ALIGN_CONTENT_SPACE_BETWEEN = 0x0091,
	MyCSS_PROPERTY_ALIGN_CONTENT_STRETCH       = 0x0095
}
typedef mycss_property_align_content_t;

enum mycss_property_align_items {
	MyCSS_PROPERTY_ALIGN_ITEMS_BASELINE   = 0x000e,
	MyCSS_PROPERTY_ALIGN_ITEMS_CENTER     = 0x0018,
	MyCSS_PROPERTY_ALIGN_ITEMS_FLEX_END   = 0x0035,
	MyCSS_PROPERTY_ALIGN_ITEMS_FLEX_START = 0x0036,
	MyCSS_PROPERTY_ALIGN_ITEMS_STRETCH    = 0x0095
}
typedef mycss_property_align_items_t;

enum mycss_property_align_self {
	MyCSS_PROPERTY_ALIGN_SELF_AUTO       = 0x000c,
	MyCSS_PROPERTY_ALIGN_SELF_BASELINE   = 0x000e,
	MyCSS_PROPERTY_ALIGN_SELF_CENTER     = 0x0018,
	MyCSS_PROPERTY_ALIGN_SELF_FLEX_END   = 0x0035,
	MyCSS_PROPERTY_ALIGN_SELF_FLEX_START = 0x0036,
	MyCSS_PROPERTY_ALIGN_SELF_STRETCH    = 0x0095
}
typedef mycss_property_align_self_t;

enum mycss_property_background_attachment {
	MyCSS_PROPERTY_BACKGROUND_ATTACHMENT_FIXED  = 0x0033,
	MyCSS_PROPERTY_BACKGROUND_ATTACHMENT_LOCAL  = 0x0058,
	MyCSS_PROPERTY_BACKGROUND_ATTACHMENT_SCROLL = 0x0084
}
typedef mycss_property_background_attachment_t;

enum mycss_property_background_clip {
	MyCSS_PROPERTY_BACKGROUND_CLIP_BORDER_BOX  = 0x0013,
	MyCSS_PROPERTY_BACKGROUND_CLIP_CONTENT_BOX = 0x0021,
	MyCSS_PROPERTY_BACKGROUND_CLIP_PADDING_BOX = 0x0070
}
typedef mycss_property_background_clip_t;

enum mycss_property_background_color {
	MyCSS_PROPERTY_BACKGROUND_COLOR_NONE = 0x0066
}
typedef mycss_property_background_color_t;

enum mycss_property_background_image {
	MyCSS_PROPERTY_BACKGROUND_IMAGE_NONE = 0x0066
}
typedef mycss_property_background_image_t;

enum mycss_property_background_origin {
	MyCSS_PROPERTY_BACKGROUND_ORIGIN_BORDER_BOX  = 0x0013,
	MyCSS_PROPERTY_BACKGROUND_ORIGIN_CONTENT_BOX = 0x0021,
	MyCSS_PROPERTY_BACKGROUND_ORIGIN_PADDING_BOX = 0x0070
}
typedef mycss_property_background_origin_t;

enum mycss_property_background_position {
	MyCSS_PROPERTY_BACKGROUND_POSITION_BOTTOM = 0x0016,
	MyCSS_PROPERTY_BACKGROUND_POSITION_CENTER = 0x0018,
	MyCSS_PROPERTY_BACKGROUND_POSITION_LEFT   = 0x0052,
	MyCSS_PROPERTY_BACKGROUND_POSITION_RIGHT  = 0x007a,
	MyCSS_PROPERTY_BACKGROUND_POSITION_TOP    = 0x00a4
}
typedef mycss_property_background_position_t;

enum mycss_property_background_repeat {
	MyCSS_PROPERTY_BACKGROUND_REPEAT_NO_REPEAT = 0x0065,
	MyCSS_PROPERTY_BACKGROUND_REPEAT_REPEAT    = 0x0076,
	MyCSS_PROPERTY_BACKGROUND_REPEAT_REPEAT_X  = 0x0077,
	MyCSS_PROPERTY_BACKGROUND_REPEAT_REPEAT_Y  = 0x0078,
	MyCSS_PROPERTY_BACKGROUND_REPEAT_ROUND     = 0x007b,
	MyCSS_PROPERTY_BACKGROUND_REPEAT_SPACE     = 0x008f
}
typedef mycss_property_background_repeat_t;

enum mycss_property_background_size {
	MyCSS_PROPERTY_BACKGROUND_SIZE_AUTO    = 0x000c,
	MyCSS_PROPERTY_BACKGROUND_SIZE_CONTAIN = 0x001f,
	MyCSS_PROPERTY_BACKGROUND_SIZE_COVER   = 0x0025
}
typedef mycss_property_background_size_t;

enum mycss_property_border_bottom_style {
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_DASHED = 0x0026,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_DOTTED = 0x002b,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_DOUBLE = 0x002c,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_GROOVE = 0x003b,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_HIDDEN = 0x003c,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_INSET  = 0x0049,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_NONE   = 0x0066,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_OUTSET = 0x006e,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_RIDGE  = 0x0079,
	MyCSS_PROPERTY_BORDER_BOTTOM_STYLE_SOLID  = 0x008e
}
typedef mycss_property_border_bottom_style_t;

enum mycss_property_border_image_repeat {
	MyCSS_PROPERTY_BORDER_IMAGE_REPEAT_REPEAT  = 0x0076,
	MyCSS_PROPERTY_BORDER_IMAGE_REPEAT_ROUND   = 0x007b,
	MyCSS_PROPERTY_BORDER_IMAGE_REPEAT_SPACE   = 0x008f,
	MyCSS_PROPERTY_BORDER_IMAGE_REPEAT_STRETCH = 0x0095
}
typedef mycss_property_border_image_repeat_t;

enum mycss_property_border_image_slice {
	MyCSS_PROPERTY_BORDER_IMAGE_SLICE_FILL = 0x0031
}
typedef mycss_property_border_image_slice_t;

enum mycss_property_border_image_width {
	MyCSS_PROPERTY_BORDER_IMAGE_WIDTH_AUTO = 0x000c
}
typedef mycss_property_border_image_width_t;

enum mycss_property_border_left_style {
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_DASHED = 0x0026,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_DOTTED = 0x002b,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_DOUBLE = 0x002c,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_GROOVE = 0x003b,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_HIDDEN = 0x003c,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_INSET  = 0x0049,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_NONE   = 0x0066,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_OUTSET = 0x006e,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_RIDGE  = 0x0079,
	MyCSS_PROPERTY_BORDER_LEFT_STYLE_SOLID  = 0x008e
}
typedef mycss_property_border_left_style_t;

enum mycss_property_border_right_style {
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_DASHED = 0x0026,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_DOTTED = 0x002b,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_DOUBLE = 0x002c,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_GROOVE = 0x003b,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_HIDDEN = 0x003c,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_INSET  = 0x0049,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_NONE   = 0x0066,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_OUTSET = 0x006e,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_RIDGE  = 0x0079,
	MyCSS_PROPERTY_BORDER_RIGHT_STYLE_SOLID  = 0x008e
}
typedef mycss_property_border_right_style_t;

enum mycss_property_border_top_style {
	MyCSS_PROPERTY_BORDER_TOP_STYLE_DASHED = 0x0026,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_DOTTED = 0x002b,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_DOUBLE = 0x002c,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_GROOVE = 0x003b,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_HIDDEN = 0x003c,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_INSET  = 0x0049,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_NONE   = 0x0066,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_OUTSET = 0x006e,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_RIDGE  = 0x0079,
	MyCSS_PROPERTY_BORDER_TOP_STYLE_SOLID  = 0x008e
}
typedef mycss_property_border_top_style_t;

enum mycss_property_box_shadow {
	MyCSS_PROPERTY_BOX_SHADOW_NONE = 0x0066
}
typedef mycss_property_box_shadow_t;

enum mycss_property_box_suppress {
	MyCSS_PROPERTY_BOX_SUPPRESS_DISCARD = 0x0029,
	MyCSS_PROPERTY_BOX_SUPPRESS_HIDE    = 0x003d,
	MyCSS_PROPERTY_BOX_SUPPRESS_SHOW    = 0x0087
}
typedef mycss_property_box_suppress_t;

enum mycss_property_clear {
	MyCSS_PROPERTY_CLEAR_BOTH  = 0x0015,
	MyCSS_PROPERTY_CLEAR_LEFT  = 0x0052,
	MyCSS_PROPERTY_CLEAR_NONE  = 0x0066,
	MyCSS_PROPERTY_CLEAR_RIGHT = 0x007a
}
typedef mycss_property_clear_t;

enum mycss_property_clear_after {
	MyCSS_PROPERTY_CLEAR_AFTER_BOTH        = 0x0015,
	MyCSS_PROPERTY_CLEAR_AFTER_BOTTOM      = 0x0016,
	MyCSS_PROPERTY_CLEAR_AFTER_DESCENDANTS = 0x0027,
	MyCSS_PROPERTY_CLEAR_AFTER_END         = 0x002d,
	MyCSS_PROPERTY_CLEAR_AFTER_INSIDE      = 0x004a,
	MyCSS_PROPERTY_CLEAR_AFTER_LEFT        = 0x0052,
	MyCSS_PROPERTY_CLEAR_AFTER_NONE        = 0x0066,
	MyCSS_PROPERTY_CLEAR_AFTER_OUTSIDE     = 0x006f,
	MyCSS_PROPERTY_CLEAR_AFTER_RIGHT       = 0x007a,
	MyCSS_PROPERTY_CLEAR_AFTER_START       = 0x0093,
	MyCSS_PROPERTY_CLEAR_AFTER_TOP         = 0x00a4
}
typedef mycss_property_clear_after_t;

enum mycss_property_display {
	MyCSS_PROPERTY_DISPLAY_BLOCK               = 0x000f,
	MyCSS_PROPERTY_DISPLAY_CONTENTS            = 0x0023,
	MyCSS_PROPERTY_DISPLAY_FLEX                = 0x0034,
	MyCSS_PROPERTY_DISPLAY_FLOW                = 0x0037,
	MyCSS_PROPERTY_DISPLAY_FLOW_ROOT           = 0x0038,
	MyCSS_PROPERTY_DISPLAY_GRID                = 0x003a,
	MyCSS_PROPERTY_DISPLAY_INLINE              = 0x0043,
	MyCSS_PROPERTY_DISPLAY_INLINE_BLOCK        = 0x0044,
	MyCSS_PROPERTY_DISPLAY_INLINE_FLEX         = 0x0045,
	MyCSS_PROPERTY_DISPLAY_INLINE_GRID         = 0x0046,
	MyCSS_PROPERTY_DISPLAY_INLINE_LIST_ITEM    = 0x0047,
	MyCSS_PROPERTY_DISPLAY_INLINE_TABLE        = 0x0048,
	MyCSS_PROPERTY_DISPLAY_LIST_ITEM           = 0x0057,
	MyCSS_PROPERTY_DISPLAY_NONE                = 0x0066,
	MyCSS_PROPERTY_DISPLAY_RUBY                = 0x007e,
	MyCSS_PROPERTY_DISPLAY_RUBY_BASE           = 0x007f,
	MyCSS_PROPERTY_DISPLAY_RUBY_BASE_CONTAINER = 0x0080,
	MyCSS_PROPERTY_DISPLAY_RUBY_TEXT           = 0x0081,
	MyCSS_PROPERTY_DISPLAY_RUBY_TEXT_CONTAINER = 0x0082,
	MyCSS_PROPERTY_DISPLAY_RUN_IN              = 0x0083,
	MyCSS_PROPERTY_DISPLAY_TABLE               = 0x0099,
	MyCSS_PROPERTY_DISPLAY_TABLE_CAPTION       = 0x009a,
	MyCSS_PROPERTY_DISPLAY_TABLE_CELL          = 0x009b,
	MyCSS_PROPERTY_DISPLAY_TABLE_COLUMN        = 0x009c,
	MyCSS_PROPERTY_DISPLAY_TABLE_COLUMN_GROUP  = 0x009d,
	MyCSS_PROPERTY_DISPLAY_TABLE_FOOTER_GROUP  = 0x009e,
	MyCSS_PROPERTY_DISPLAY_TABLE_HEADER_GROUP  = 0x009f,
	MyCSS_PROPERTY_DISPLAY_TABLE_ROW           = 0x00a0,
	MyCSS_PROPERTY_DISPLAY_TABLE_ROW_GROUP     = 0x00a1
}
typedef mycss_property_display_t;

enum mycss_property_flex {
	MyCSS_PROPERTY_FLEX_NONE = 0x0066
}
typedef mycss_property_flex_t;

enum mycss_property_flex_basis {
	MyCSS_PROPERTY_FLEX_BASIS_AUTO    = 0x000c,
	MyCSS_PROPERTY_FLEX_BASIS_CONTENT = 0x0020
}
typedef mycss_property_flex_basis_t;

enum mycss_property_flex_direction {
	MyCSS_PROPERTY_FLEX_DIRECTION_COLUMN         = 0x001a,
	MyCSS_PROPERTY_FLEX_DIRECTION_COLUMN_REVERSE = 0x001b,
	MyCSS_PROPERTY_FLEX_DIRECTION_ROW            = 0x007c,
	MyCSS_PROPERTY_FLEX_DIRECTION_ROW_REVERSE    = 0x007d
}
typedef mycss_property_flex_direction_t;

enum mycss_property_flex_flow {
	MyCSS_PROPERTY_FLEX_FLOW_COLUMN         = 0x001a,
	MyCSS_PROPERTY_FLEX_FLOW_COLUMN_REVERSE = 0x001b,
	MyCSS_PROPERTY_FLEX_FLOW_NOWRAP         = 0x0068,
	MyCSS_PROPERTY_FLEX_FLOW_ROW            = 0x007c,
	MyCSS_PROPERTY_FLEX_FLOW_ROW_REVERSE    = 0x007d,
	MyCSS_PROPERTY_FLEX_FLOW_WRAP           = 0x00ab,
	MyCSS_PROPERTY_FLEX_FLOW_WRAP_REVERSE   = 0x00ac
}
typedef mycss_property_flex_flow_t;

enum mycss_property_flex_wrap {
	MyCSS_PROPERTY_FLEX_WRAP_NOWRAP       = 0x0068,
	MyCSS_PROPERTY_FLEX_WRAP_WRAP         = 0x00ab,
	MyCSS_PROPERTY_FLEX_WRAP_WRAP_REVERSE = 0x00ac
}
typedef mycss_property_flex_wrap_t;

enum mycss_property_float {
	MyCSS_PROPERTY_FLOAT_BOTTOM = 0x0016,
	MyCSS_PROPERTY_FLOAT_END    = 0x002d,
	MyCSS_PROPERTY_FLOAT_LEFT   = 0x0052,
	MyCSS_PROPERTY_FLOAT_NONE   = 0x0066,
	MyCSS_PROPERTY_FLOAT_RIGHT  = 0x007a,
	MyCSS_PROPERTY_FLOAT_START  = 0x0093,
	MyCSS_PROPERTY_FLOAT_TOP    = 0x00a4
}
typedef mycss_property_float_t;

enum mycss_property_float_displace {
	MyCSS_PROPERTY_FLOAT_DISPLACE_BLOCK             = 0x000f,
	MyCSS_PROPERTY_FLOAT_DISPLACE_BLOCK_WITHIN_PAGE = 0x0010,
	MyCSS_PROPERTY_FLOAT_DISPLACE_INDENT            = 0x0041,
	MyCSS_PROPERTY_FLOAT_DISPLACE_LINE              = 0x0055
}
typedef mycss_property_float_displace_t;

enum mycss_property_font {
	MyCSS_PROPERTY_FONT_CAPTION       = 0x0017,
	MyCSS_PROPERTY_FONT_ICON          = 0x0040,
	MyCSS_PROPERTY_FONT_MENU          = 0x005c,
	MyCSS_PROPERTY_FONT_MESSAGE_BOX   = 0x005d,
	MyCSS_PROPERTY_FONT_NORMAL        = 0x0067,
	MyCSS_PROPERTY_FONT_SMALL_CAPS    = 0x008b,
	MyCSS_PROPERTY_FONT_SMALL_CAPTION = 0x008c,
	MyCSS_PROPERTY_FONT_STATUS_BAR    = 0x0094
}
typedef mycss_property_font_t;

enum mycss_property_font_feature_settings {
	MyCSS_PROPERTY_FONT_FEATURE_SETTINGS_NORMAL = 0x0067,
	MyCSS_PROPERTY_FONT_FEATURE_SETTINGS_OFF    = 0x006a,
	MyCSS_PROPERTY_FONT_FEATURE_SETTINGS_ON     = 0x006c
}
typedef mycss_property_font_feature_settings_t;

enum mycss_property_font_kerning {
	MyCSS_PROPERTY_FONT_KERNING_AUTO   = 0x000c,
	MyCSS_PROPERTY_FONT_KERNING_NONE   = 0x0066,
	MyCSS_PROPERTY_FONT_KERNING_NORMAL = 0x0067
}
typedef mycss_property_font_kerning_t;

enum mycss_property_font_language_override {
	MyCSS_PROPERTY_FONT_LANGUAGE_OVERRIDE_NORMAL = 0x0067
}
typedef mycss_property_font_language_override_t;

enum mycss_property_font_size {
	MyCSS_PROPERTY_FONT_SIZE_LARGE    = 0x0050,
	MyCSS_PROPERTY_FONT_SIZE_LARGER   = 0x0051,
	MyCSS_PROPERTY_FONT_SIZE_MEDIUM   = 0x005b,
	MyCSS_PROPERTY_FONT_SIZE_SMALL    = 0x008a,
	MyCSS_PROPERTY_FONT_SIZE_SMALLER  = 0x008d,
	MyCSS_PROPERTY_FONT_SIZE_X_LARGE  = 0x00ad,
	MyCSS_PROPERTY_FONT_SIZE_X_SMALL  = 0x00ae,
	MyCSS_PROPERTY_FONT_SIZE_XX_LARGE = 0x00af,
	MyCSS_PROPERTY_FONT_SIZE_XX_SMALL = 0x00b0
}
typedef mycss_property_font_size_t;

enum mycss_property_font_size_adjust {
	MyCSS_PROPERTY_FONT_SIZE_ADJUST_NONE = 0x0066
}
typedef mycss_property_font_size_adjust_t;

enum mycss_property_font_stretch {
	MyCSS_PROPERTY_FONT_STRETCH_CONDENSED       = 0x001e,
	MyCSS_PROPERTY_FONT_STRETCH_EXPANDED        = 0x002e,
	MyCSS_PROPERTY_FONT_STRETCH_EXTRA_CONDENSED = 0x002f,
	MyCSS_PROPERTY_FONT_STRETCH_EXTRA_EXPANDED  = 0x0030,
	MyCSS_PROPERTY_FONT_STRETCH_NORMAL          = 0x0067,
	MyCSS_PROPERTY_FONT_STRETCH_SEMI_CONDENSED  = 0x0085,
	MyCSS_PROPERTY_FONT_STRETCH_SEMI_EXPANDED   = 0x0086,
	MyCSS_PROPERTY_FONT_STRETCH_ULTRA_CONDENSED = 0x00a6,
	MyCSS_PROPERTY_FONT_STRETCH_ULTRA_EXPANDED  = 0x00a7
}
typedef mycss_property_font_stretch_t;

enum mycss_property_font_style {
	MyCSS_PROPERTY_FONT_STYLE_ITALIC  = 0x004b,
	MyCSS_PROPERTY_FONT_STYLE_NORMAL  = 0x0067,
	MyCSS_PROPERTY_FONT_STYLE_OBLIQUE = 0x0069
}
typedef mycss_property_font_style_t;

enum mycss_property_font_synthesis {
	MyCSS_PROPERTY_FONT_SYNTHESIS_NONE   = 0x0066,
	MyCSS_PROPERTY_FONT_SYNTHESIS_STYLE  = 0x0096,
	MyCSS_PROPERTY_FONT_SYNTHESIS_WEIGHT = 0x00aa
}
typedef mycss_property_font_synthesis_t;

enum mycss_property_font_variant {
	MyCSS_PROPERTY_FONT_VARIANT_ALL_PETITE_CAPS  = 0x000a,
	MyCSS_PROPERTY_FONT_VARIANT_ALL_SMALL_CAPS   = 0x000b,
	MyCSS_PROPERTY_FONT_VARIANT_HISTORICAL_FORMS = 0x003e,
	MyCSS_PROPERTY_FONT_VARIANT_NONE             = 0x0066,
	MyCSS_PROPERTY_FONT_VARIANT_NORMAL           = 0x0067,
	MyCSS_PROPERTY_FONT_VARIANT_ORDINAL          = 0x006d,
	MyCSS_PROPERTY_FONT_VARIANT_PETITE_CAPS      = 0x0073,
	MyCSS_PROPERTY_FONT_VARIANT_RUBY             = 0x007e,
	MyCSS_PROPERTY_FONT_VARIANT_SLASHED_ZERO     = 0x0089,
	MyCSS_PROPERTY_FONT_VARIANT_SMALL_CAPS       = 0x008b,
	MyCSS_PROPERTY_FONT_VARIANT_SUB              = 0x0097,
	MyCSS_PROPERTY_FONT_VARIANT_SUPER            = 0x0098,
	MyCSS_PROPERTY_FONT_VARIANT_TITLING_CAPS     = 0x00a3,
	MyCSS_PROPERTY_FONT_VARIANT_UNICASE          = 0x00a8
}
typedef mycss_property_font_variant_t;

enum mycss_property_font_variant_alternates {
	MyCSS_PROPERTY_FONT_VARIANT_ALTERNATES_HISTORICAL_FORMS = 0x003e,
	MyCSS_PROPERTY_FONT_VARIANT_ALTERNATES_NORMAL           = 0x0067
}
typedef mycss_property_font_variant_alternates_t;

enum mycss_property_font_variant_caps {
	MyCSS_PROPERTY_FONT_VARIANT_CAPS_ALL_PETITE_CAPS = 0x000a,
	MyCSS_PROPERTY_FONT_VARIANT_CAPS_ALL_SMALL_CAPS  = 0x000b,
	MyCSS_PROPERTY_FONT_VARIANT_CAPS_NORMAL          = 0x0067,
	MyCSS_PROPERTY_FONT_VARIANT_CAPS_PETITE_CAPS     = 0x0073,
	MyCSS_PROPERTY_FONT_VARIANT_CAPS_SMALL_CAPS      = 0x008b,
	MyCSS_PROPERTY_FONT_VARIANT_CAPS_TITLING_CAPS    = 0x00a3,
	MyCSS_PROPERTY_FONT_VARIANT_CAPS_UNICASE         = 0x00a8
}
typedef mycss_property_font_variant_caps_t;

enum mycss_property_font_variant_east_asian {
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_FULL_WIDTH         = 0x0039,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_JIS04              = 0x004c,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_JIS78              = 0x004d,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_JIS83              = 0x004e,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_JIS90              = 0x004f,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_NORMAL             = 0x0067,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_PROPORTIONAL_WIDTH = 0x0075,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_RUBY               = 0x007e,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_SIMPLIFIED         = 0x0088,
	MyCSS_PROPERTY_FONT_VARIANT_EAST_ASIAN_TRADITIONAL        = 0x00a5
}
typedef mycss_property_font_variant_east_asian_t;

enum mycss_property_font_variant_ligatures {
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_COMMON_LIGATURES           = 0x001c,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_CONTEXTUAL                 = 0x0024,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_DISCRETIONARY_LIGATURES    = 0x002a,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_HISTORICAL_LIGATURES       = 0x003f,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_NO_COMMON_LIGATURES        = 0x005f,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_NO_CONTEXTUAL              = 0x0061,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_NO_DISCRETIONARY_LIGATURES = 0x0062,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_NO_HISTORICAL_LIGATURES    = 0x0064,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_NONE                       = 0x0066,
	MyCSS_PROPERTY_FONT_VARIANT_LIGATURES_NORMAL                     = 0x0067
}
typedef mycss_property_font_variant_ligatures_t;

enum mycss_property_font_variant_numeric {
	MyCSS_PROPERTY_FONT_VARIANT_NUMERIC_DIAGONAL_FRACTIONS = 0x0028,
	MyCSS_PROPERTY_FONT_VARIANT_NUMERIC_LINING_NUMS        = 0x0056,
	MyCSS_PROPERTY_FONT_VARIANT_NUMERIC_NORMAL             = 0x0067,
	MyCSS_PROPERTY_FONT_VARIANT_NUMERIC_OLDSTYLE_NUMS      = 0x006b,
	MyCSS_PROPERTY_FONT_VARIANT_NUMERIC_PROPORTIONAL_NUMS  = 0x0074,
	MyCSS_PROPERTY_FONT_VARIANT_NUMERIC_STACKED_FRACTIONS  = 0x0092,
	MyCSS_PROPERTY_FONT_VARIANT_NUMERIC_TABULAR_NUMS       = 0x00a2
}
typedef mycss_property_font_variant_numeric_t;

enum mycss_property_font_variant_position {
	MyCSS_PROPERTY_FONT_VARIANT_POSITION_NORMAL = 0x0067,
	MyCSS_PROPERTY_FONT_VARIANT_POSITION_SUB    = 0x0097,
	MyCSS_PROPERTY_FONT_VARIANT_POSITION_SUPER  = 0x0098
}
typedef mycss_property_font_variant_position_t;

enum mycss_property_font_weight {
	MyCSS_PROPERTY_FONT_WEIGHT_100     = 0x0001,
	MyCSS_PROPERTY_FONT_WEIGHT_200     = 0x0002,
	MyCSS_PROPERTY_FONT_WEIGHT_300     = 0x0003,
	MyCSS_PROPERTY_FONT_WEIGHT_400     = 0x0004,
	MyCSS_PROPERTY_FONT_WEIGHT_500     = 0x0005,
	MyCSS_PROPERTY_FONT_WEIGHT_600     = 0x0006,
	MyCSS_PROPERTY_FONT_WEIGHT_700     = 0x0007,
	MyCSS_PROPERTY_FONT_WEIGHT_800     = 0x0008,
	MyCSS_PROPERTY_FONT_WEIGHT_900     = 0x0009,
	MyCSS_PROPERTY_FONT_WEIGHT_BOLD    = 0x0011,
	MyCSS_PROPERTY_FONT_WEIGHT_BOLDER  = 0x0012,
	MyCSS_PROPERTY_FONT_WEIGHT_LIGHTER = 0x0054,
	MyCSS_PROPERTY_FONT_WEIGHT_NORMAL  = 0x0067
}
typedef mycss_property_font_weight_t;

enum mycss_property_height {
	MyCSS_PROPERTY_HEIGHT_AUTO        = 0x000c,
	MyCSS_PROPERTY_HEIGHT_AVAILABLE   = 0x000d,
	MyCSS_PROPERTY_HEIGHT_COMPLEX     = 0x001d,
	MyCSS_PROPERTY_HEIGHT_FIT_CONTENT = 0x0032,
	MyCSS_PROPERTY_HEIGHT_INHERIT     = 0x0042,
	MyCSS_PROPERTY_HEIGHT_LENGTH      = 0x0053,
	MyCSS_PROPERTY_HEIGHT_MAX_CONTENT = 0x005a,
	MyCSS_PROPERTY_HEIGHT_MIN_CONTENT = 0x005e,
	MyCSS_PROPERTY_HEIGHT_PERCENTAGE  = 0x0072
}
typedef mycss_property_height_t;

enum mycss_property_indent_edge_reset {
	MyCSS_PROPERTY_INDENT_EDGE_RESET_BORDER_EDGE  = 0x0014,
	MyCSS_PROPERTY_INDENT_EDGE_RESET_CONTENT_EDGE = 0x0022,
	MyCSS_PROPERTY_INDENT_EDGE_RESET_MARGIN_EDGE  = 0x0059,
	MyCSS_PROPERTY_INDENT_EDGE_RESET_NONE         = 0x0066,
	MyCSS_PROPERTY_INDENT_EDGE_RESET_PADDING_EDGE = 0x0071
}
typedef mycss_property_indent_edge_reset_t;

enum mycss_property_justify_content {
	MyCSS_PROPERTY_JUSTIFY_CONTENT_CENTER        = 0x0018,
	MyCSS_PROPERTY_JUSTIFY_CONTENT_FLEX_END      = 0x0035,
	MyCSS_PROPERTY_JUSTIFY_CONTENT_FLEX_START    = 0x0036,
	MyCSS_PROPERTY_JUSTIFY_CONTENT_SPACE_AROUND  = 0x0090,
	MyCSS_PROPERTY_JUSTIFY_CONTENT_SPACE_BETWEEN = 0x0091
}
typedef mycss_property_justify_content_t;

enum mycss_property_margin_bottom {
	MyCSS_PROPERTY_MARGIN_BOTTOM_AUTO = 0x000c
}
typedef mycss_property_margin_bottom_t;

enum mycss_property_margin_left {
	MyCSS_PROPERTY_MARGIN_LEFT_AUTO = 0x000c
}
typedef mycss_property_margin_left_t;

enum mycss_property_margin_right {
	MyCSS_PROPERTY_MARGIN_RIGHT_AUTO = 0x000c
}
typedef mycss_property_margin_right_t;

enum mycss_property_margin_top {
	MyCSS_PROPERTY_MARGIN_TOP_AUTO = 0x000c
}
typedef mycss_property_margin_top_t;

enum mycss_property_max_height {
	MyCSS_PROPERTY_MAX_HEIGHT_AVAILABLE   = 0x000d,
	MyCSS_PROPERTY_MAX_HEIGHT_BORDER_BOX  = 0x0013,
	MyCSS_PROPERTY_MAX_HEIGHT_CONTENT_BOX = 0x0021,
	MyCSS_PROPERTY_MAX_HEIGHT_FIT_CONTENT = 0x0032,
	MyCSS_PROPERTY_MAX_HEIGHT_MAX_CONTENT = 0x005a,
	MyCSS_PROPERTY_MAX_HEIGHT_MIN_CONTENT = 0x005e,
	MyCSS_PROPERTY_MAX_HEIGHT_NONE        = 0x0066
}
typedef mycss_property_max_height_t;

enum mycss_property_max_width {
	MyCSS_PROPERTY_MAX_WIDTH_AVAILABLE   = 0x000d,
	MyCSS_PROPERTY_MAX_WIDTH_BORDER_BOX  = 0x0013,
	MyCSS_PROPERTY_MAX_WIDTH_CONTENT_BOX = 0x0021,
	MyCSS_PROPERTY_MAX_WIDTH_FIT_CONTENT = 0x0032,
	MyCSS_PROPERTY_MAX_WIDTH_MAX_CONTENT = 0x005a,
	MyCSS_PROPERTY_MAX_WIDTH_MIN_CONTENT = 0x005e,
	MyCSS_PROPERTY_MAX_WIDTH_NONE        = 0x0066
}
typedef mycss_property_max_width_t;

enum mycss_property_min_height {
	MyCSS_PROPERTY_MIN_HEIGHT_AVAILABLE   = 0x000d,
	MyCSS_PROPERTY_MIN_HEIGHT_BORDER_BOX  = 0x0013,
	MyCSS_PROPERTY_MIN_HEIGHT_CONTENT_BOX = 0x0021,
	MyCSS_PROPERTY_MIN_HEIGHT_FIT_CONTENT = 0x0032,
	MyCSS_PROPERTY_MIN_HEIGHT_MAX_CONTENT = 0x005a,
	MyCSS_PROPERTY_MIN_HEIGHT_MIN_CONTENT = 0x005e
}
typedef mycss_property_min_height_t;

enum mycss_property_min_width {
	MyCSS_PROPERTY_MIN_WIDTH_AVAILABLE   = 0x000d,
	MyCSS_PROPERTY_MIN_WIDTH_BORDER_BOX  = 0x0013,
	MyCSS_PROPERTY_MIN_WIDTH_CONTENT_BOX = 0x0021,
	MyCSS_PROPERTY_MIN_WIDTH_FIT_CONTENT = 0x0032,
	MyCSS_PROPERTY_MIN_WIDTH_MAX_CONTENT = 0x005a,
	MyCSS_PROPERTY_MIN_WIDTH_MIN_CONTENT = 0x005e
}
typedef mycss_property_min_width_t;

enum mycss_property_overflow {
	MyCSS_PROPERTY_OVERFLOW_AUTO       = 0x000c,
	MyCSS_PROPERTY_OVERFLOW_HIDDEN     = 0x003c,
	MyCSS_PROPERTY_OVERFLOW_NO_CONTENT = 0x0060,
	MyCSS_PROPERTY_OVERFLOW_NO_DISPLAY = 0x0063,
	MyCSS_PROPERTY_OVERFLOW_SCROLL     = 0x0084,
	MyCSS_PROPERTY_OVERFLOW_VISIBLE    = 0x00a9
}
typedef mycss_property_overflow_t;

enum mycss_property_overflow_x {
	MyCSS_PROPERTY_OVERFLOW_X_AUTO       = 0x000c,
	MyCSS_PROPERTY_OVERFLOW_X_HIDDEN     = 0x003c,
	MyCSS_PROPERTY_OVERFLOW_X_NO_CONTENT = 0x0060,
	MyCSS_PROPERTY_OVERFLOW_X_NO_DISPLAY = 0x0063,
	MyCSS_PROPERTY_OVERFLOW_X_SCROLL     = 0x0084,
	MyCSS_PROPERTY_OVERFLOW_X_VISIBLE    = 0x00a9
}
typedef mycss_property_overflow_x_t;

enum mycss_property_overflow_y {
	MyCSS_PROPERTY_OVERFLOW_Y_AUTO       = 0x000c,
	MyCSS_PROPERTY_OVERFLOW_Y_HIDDEN     = 0x003c,
	MyCSS_PROPERTY_OVERFLOW_Y_NO_CONTENT = 0x0060,
	MyCSS_PROPERTY_OVERFLOW_Y_NO_DISPLAY = 0x0063,
	MyCSS_PROPERTY_OVERFLOW_Y_SCROLL     = 0x0084,
	MyCSS_PROPERTY_OVERFLOW_Y_VISIBLE    = 0x00a9
}
typedef mycss_property_overflow_y_t;

enum mycss_property_visibility {
	MyCSS_PROPERTY_VISIBILITY_COLLAPSE = 0x0019,
	MyCSS_PROPERTY_VISIBILITY_HIDDEN   = 0x003c,
	MyCSS_PROPERTY_VISIBILITY_VISIBLE  = 0x00a9
}
typedef mycss_property_visibility_t;

enum mycss_property_width {
	MyCSS_PROPERTY_WIDTH_AUTO        = 0x000c,
	MyCSS_PROPERTY_WIDTH_AVAILABLE   = 0x000d,
	MyCSS_PROPERTY_WIDTH_FIT_CONTENT = 0x0032,
	MyCSS_PROPERTY_WIDTH_INHERIT     = 0x0042,
	MyCSS_PROPERTY_WIDTH_LENGTH      = 0x0053,
	MyCSS_PROPERTY_WIDTH_MAX_CONTENT = 0x005a,
	MyCSS_PROPERTY_WIDTH_MIN_CONTENT = 0x005e,
	MyCSS_PROPERTY_WIDTH_PERCENTAGE  = 0x0072
}
typedef mycss_property_width_t;



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MyHTML_MyCSS_PROPERTY_CONST_H */


